-- PILOTDATA. Generert av scripts/build-pilot-seed.mjs fra supabase/pilot/skoler.csv. Ikke rediger for hånd.
-- 15 fylkesstyrer og 471 medlemsskoler fra Elevorganisasjonens medlemsregister 2025/2026.
-- Oppdaterer etter ekstern ID, så filen kan kjøres flere ganger.

insert into public.organizations(type,external_id,name,slug,county,status,is_placeholder)
select 'county_board',v.external_id,v.name,v.slug,v.county,'active',false
from (values
  ('eo-fylke-agder','Elevorganisasjonen i Agder','fylke-agder','Agder'),
  ('eo-fylke-akershus','Elevorganisasjonen i Akershus','fylke-akershus','Akershus'),
  ('eo-fylke-buskerud','Elevorganisasjonen i Buskerud','fylke-buskerud','Buskerud'),
  ('eo-fylke-finnmark','Elevorganisasjonen i Finnmark','fylke-finnmark','Finnmark'),
  ('eo-fylke-innlandet','Elevorganisasjonen i Innlandet','fylke-innlandet','Innlandet'),
  ('eo-fylke-more-og-romsdal','Elevorganisasjonen i Møre og Romsdal','fylke-more-og-romsdal','Møre og Romsdal'),
  ('eo-fylke-nordland','Elevorganisasjonen i Nordland','fylke-nordland','Nordland'),
  ('eo-fylke-oslo','Elevorganisasjonen i Oslo','fylke-oslo','Oslo'),
  ('eo-fylke-rogaland','Elevorganisasjonen i Rogaland','fylke-rogaland','Rogaland'),
  ('eo-fylke-telemark','Elevorganisasjonen i Telemark','fylke-telemark','Telemark'),
  ('eo-fylke-troms','Elevorganisasjonen i Troms','fylke-troms','Troms'),
  ('eo-fylke-trondelag','Elevorganisasjonen i Trøndelag','fylke-trondelag','Trøndelag'),
  ('eo-fylke-vestfold','Elevorganisasjonen i Vestfold','fylke-vestfold','Vestfold'),
  ('eo-fylke-vestland','Elevorganisasjonen i Vestland','fylke-vestland','Vestland'),
  ('eo-fylke-ostfold','Elevorganisasjonen i Østfold','fylke-ostfold','Østfold')
) as v(external_id,name,slug,county)
on conflict(external_id) do update set name=excluded.name,slug=excluded.slug,county=excluded.county;

insert into public.organizations(type,external_id,name,school_name,slug,organization_number,county,local_board_id,school_level,contact_email,status,is_placeholder)
select 'school',v.external_id,v.name,v.name,v.slug,v.organization_number,v.county,lb.id,v.school_level,v.contact_email,v.status::public.organization_status,false
from (values
  ('eo-skole-arendal-videregaende-skole-avd-tyholmen-og-barbu','Arendal videregående skole (avd. Tyholmen og Barbu)','arendal-videregaende-skole-avd-tyholmen-og-barbu',null,'Agder',null,'upper_secondary',null,'active'),
  ('eo-skole-dahlske-videregaende-skole','Dahlske videregående skole','dahlske-videregaende-skole',null,'Agder',null,'upper_secondary',null,'active'),
  ('eo-skole-eilert-sundt-videregaende-skole-avd-farsund','Eilert Sundt videregående skole (avd Farsund)','eilert-sundt-videregaende-skole-avd-farsund',null,'Agder',null,'upper_secondary',null,'active'),
  ('eo-skole-eilert-sundt-videregaende-skole-avd-lyngdal','Eilert Sundt videregående skole (avd Lyngdal)','eilert-sundt-videregaende-skole-avd-lyngdal',null,'Agder',null,'upper_secondary',null,'active'),
  ('eo-skole-flekkefjord-vgs-avd-kvinesdal','Flekkefjord vgs, avd Kvinesdal','flekkefjord-vgs-avd-kvinesdal',null,'Agder',null,'upper_secondary',null,'active'),
  ('eo-skole-flekkefjord-videregaende-skole-avd-flekkefjord','Flekkefjord videregående skole, avd Flekkefjord','flekkefjord-videregaende-skole-avd-flekkefjord',null,'Agder',null,'upper_secondary',null,'active'),
  ('eo-skole-grim-skole','Grim skole','grim-skole',null,'Agder',null,'lower_secondary',null,'active'),
  ('eo-skole-kristiansand-katedralskole-gimle','Kristiansand Katedralskole Gimle','kristiansand-katedralskole-gimle',null,'Agder',null,'upper_secondary',null,'active'),
  ('eo-skole-kvadraturen-videregaende-skole','Kvadraturen videregående skole','kvadraturen-videregaende-skole',null,'Agder',null,'upper_secondary',null,'active'),
  ('eo-skole-lillesand-videregaende-skole','Lillesand videregående skole','lillesand-videregaende-skole',null,'Agder',null,'upper_secondary',null,'active'),
  ('eo-skole-mandal-videregaende-skole','Mandal videregående skole','mandal-videregaende-skole',null,'Agder',null,'upper_secondary',null,'active'),
  ('eo-skole-nedenes-skole','Nedenes skole','nedenes-skole',null,'Agder',null,'lower_secondary',null,'active'),
  ('eo-skole-risor-videregaende-skole','Risør videregående skole','risor-videregaende-skole',null,'Agder',null,'upper_secondary',null,'active'),
  ('eo-skole-sam-eyde-videregaende-skole','Sam Eyde videregående skole','sam-eyde-videregaende-skole',null,'Agder',null,'upper_secondary',null,'active'),
  ('eo-skole-setesdal-videregaende-skole','Setesdal videregående skole','setesdal-videregaende-skole',null,'Agder',null,'upper_secondary',null,'active'),
  ('eo-skole-sogndalen-ungsomsskole','Sogndalen ungsomsskole','sogndalen-ungsomsskole',null,'Agder',null,'lower_secondary',null,'active'),
  ('eo-skole-steinerskolen-i-kristiansand','Steinerskolen i Kristiansand','steinerskolen-i-kristiansand',null,'Agder',null,'lower_secondary',null,'active'),
  ('eo-skole-sogne-videregaende-skole','Søgne videregående skole','sogne-videregaende-skole',null,'Agder',null,'upper_secondary',null,'active'),
  ('eo-skole-tangen-videregaende-skole','Tangen videregående skole','tangen-videregaende-skole',null,'Agder',null,'upper_secondary',null,'active'),
  ('eo-skole-torridal-ungdomsskole','Torridal ungdomsskole','torridal-ungdomsskole',null,'Agder',null,'lower_secondary',null,'active'),
  ('eo-skole-tvedestrand-videregaende-skole','Tvedestrand Videregående skole','tvedestrand-videregaende-skole',null,'Agder',null,'upper_secondary',null,'active'),
  ('eo-skole-valle-skule','Valle skule','valle-skule',null,'Agder',null,'lower_secondary',null,'active'),
  ('eo-skole-vennesla-videregaende-skole','Vennesla videregående skole','vennesla-videregaende-skole',null,'Agder',null,'upper_secondary',null,'active'),
  ('eo-skole-vagsbygd-videregaende-skole','Vågsbygd videregående skole','vagsbygd-videregaende-skole',null,'Agder',null,'upper_secondary',null,'active'),
  ('eo-skole-akademiet-realfagsgymnas-sandvika','Akademiet Realfagsgymnas Sandvika','akademiet-realfagsgymnas-sandvika',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-alvaern-ungdomsskole','Alværn ungdomsskole','alvaern-ungdomsskole',null,'Akershus',null,'lower_secondary',null,'active'),
  ('eo-skole-asker-videregaende-skole','Asker videregående skole','asker-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-aursmoen-skole','Aursmoen skole','aursmoen-skole',null,'Akershus',null,'lower_secondary',null,'active'),
  ('eo-skole-bakkelokka-ungdomsskole','Bakkeløkka ungdomsskole','bakkelokka-ungdomsskole',null,'Akershus',null,'lower_secondary',null,'active'),
  ('eo-skole-bjorkelangen-videregaende-skole','Bjørkelangen videregående skole','bjorkelangen-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-bleiker-videregaende-skole','Bleiker videregående skole','bleiker-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-dromtorp-videregaende-skole','Drømtorp videregående skole','dromtorp-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-dyrlokkeasen-skole','Dyrløkkeåsen skole','dyrlokkeasen-skole',null,'Akershus',null,'lower_secondary',null,'active'),
  ('eo-skole-donski-videregaende-skole','Dønski videregående skole','donski-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-eidsvoll-videregaende-skole','Eidsvoll videregående skole','eidsvoll-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-floysbonn-skole','Fløysbonn skole','floysbonn-skole',null,'Akershus',null,'lower_secondary',null,'active'),
  ('eo-skole-gjettum-skole','Gjettum skole','gjettum-skole',null,'Akershus',null,'lower_secondary',null,'active'),
  ('eo-skole-harestua-skole-ungdomsskolen','Harestua skole, ungdomsskolen','harestua-skole-ungdomsskolen',null,'Akershus',null,'lower_secondary',null,'active'),
  ('eo-skole-haugjordet-ungdomsskole','Haugjordet ungdomsskole','haugjordet-ungdomsskole',null,'Akershus',null,'lower_secondary',null,'active'),
  ('eo-skole-hovedgarden-ungdomsskole','Hovedgården ungdomsskole','hovedgarden-ungdomsskole',null,'Akershus',null,'lower_secondary',null,'active'),
  ('eo-skole-hvam-videregaende-skole','Hvam videregående skole','hvam-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-jessheim-videregaende-skole','Jessheim videregående skole','jessheim-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-lillestrom-videregaende-skole','Lillestrøm videregående skole','lillestrom-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-marikollen-ungdomsskole','Marikollen ungdomsskole','marikollen-ungdomsskole',null,'Akershus',null,'lower_secondary',null,'active'),
  ('eo-skole-nadderud-videregaende-skole','Nadderud videregående skole','nadderud-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-nannestad-videregaende-skole','Nannestad videregående skole','nannestad-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-nesbru-videregaende-skole','Nesbru videregående skole','nesbru-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-nesodden-videregaende-skole','Nesodden videregående skole','nesodden-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-nordbytun-ungdomsskole','Nordbytun ungdomsskole','nordbytun-ungdomsskole',null,'Akershus',null,'lower_secondary',null,'active'),
  ('eo-skole-ramstad-skole','Ramstad skole','ramstad-skole',null,'Akershus',null,'lower_secondary',null,'active'),
  ('eo-skole-roald-amundsen-videregaende-skole','Roald Amundsen videregående skole','roald-amundsen-videregaende-skole',null,'Akershus',null,'lower_secondary',null,'active'),
  ('eo-skole-rosenvilde-videregaende-skole','Rosenvilde videregående skole','rosenvilde-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-rud-videregaende-skole','Rud videregående skole','rud-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-rudolf-steinerskolen-stiftelsen-avd-undervisning-nesodden','Rudolf Steinerskolen stiftelsen avd. Undervisning (Nesodden)','rudolf-steinerskolen-stiftelsen-avd-undervisning-nesodden',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-raelingen-videregaende-skole','Rælingen videregående skole','raelingen-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-royken-ungdomsskole','Røyken ungdomsskole','royken-ungdomsskole',null,'Akershus',null,'lower_secondary',null,'active'),
  ('eo-skole-royken-videregaende-skole','Røyken videregående skole','royken-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-sandvika-videregaende-skole','Sandvika videregående skole','sandvika-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-ski-videregaende-skole','Ski videregående skole','ski-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-stabekk-videregaende-skole','Stabekk videregående skole','stabekk-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-steinerskolen-pa-eidsvoll','Steinerskolen på Eidsvoll','steinerskolen-pa-eidsvoll',null,'Akershus',null,'lower_secondary',null,'active'),
  ('eo-skole-strommen-videregaende-skole','Strømmen videregående skole','strommen-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-svensedammen-ungdomsskole','Svensedammen ungdomsskole','svensedammen-ungdomsskole',null,'Akershus',null,'lower_secondary',null,'active'),
  ('eo-skole-sorumsand-videregaende-skole','Sørumsand videregående skole','sorumsand-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-tangenasen-ungdomsskole','Tangenåsen ungdomsskole','tangenasen-ungdomsskole',null,'Akershus',null,'lower_secondary',null,'active'),
  ('eo-skole-valler-videregaende-skole','Valler videregående skole','valler-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-vestby-ungdomsskole','Vestby ungdomsskole','vestby-ungdomsskole',null,'Akershus',null,'lower_secondary',null,'active'),
  ('eo-skole-vestby-videregaende-skole','Vestby videregående skole','vestby-videregaende-skole',null,'Akershus',null,'upper_secondary',null,'active'),
  ('eo-skole-vollen-ungdomsskole','Vollen ungdomsskole','vollen-ungdomsskole',null,'Akershus',null,'lower_secondary',null,'active'),
  ('eo-skole-as-ungdomsskole','Ås ungdomsskole','as-ungdomsskole',null,'Akershus',null,'lower_secondary',null,'active'),
  ('eo-skole-akademiet-drammen-as','Akademiet Drammen AS','akademiet-drammen-as',null,'Buskerud',null,'upper_secondary',null,'active'),
  ('eo-skole-akademiet-ypsilon-videregaende-skole-as','Akademiet Ypsilon videregående skole AS','akademiet-ypsilon-videregaende-skole-as',null,'Buskerud',null,'upper_secondary',null,'active'),
  ('eo-skole-briskeby-videregaende-skole-as','Briskeby videregående skole AS','briskeby-videregaende-skole-as',null,'Buskerud',null,'upper_secondary',null,'active'),
  ('eo-skole-buskerud-videregaende-skole-avd-rosthaug','Buskerud videregående skole avd. Rosthaug','buskerud-videregaende-skole-avd-rosthaug',null,'Buskerud',null,'upper_secondary',null,'active'),
  ('eo-skole-drammen-videregaende-skole','Drammen videregående skole','drammen-videregaende-skole',null,'Buskerud',null,'upper_secondary',null,'active'),
  ('eo-skole-eiker-videregaende-skole','Eiker videregående skole','eiker-videregaende-skole',null,'Buskerud',null,'upper_secondary',null,'active'),
  ('eo-skole-gol-videregaende-skole','Gol videregående skole','gol-videregaende-skole',null,'Buskerud',null,'upper_secondary',null,'active'),
  ('eo-skole-hokksund-ungdomsskole','Hokksund ungdomsskole','hokksund-ungdomsskole',null,'Buskerud',null,'lower_secondary',null,'active'),
  ('eo-skole-honefoss-videregaende-skole','Hønefoss videregående skole','honefoss-videregaende-skole',null,'Buskerud',null,'upper_secondary',null,'active'),
  ('eo-skole-kongsberg-videregaende-skole','Kongsberg videregående skole','kongsberg-videregaende-skole',null,'Buskerud',null,'upper_secondary',null,'active'),
  ('eo-skole-lier-videregaende-skole','Lier videregående skole','lier-videregaende-skole',null,'Buskerud',null,'upper_secondary',null,'active'),
  ('eo-skole-numedal-videregaende-skole','Numedal videregående skole','numedal-videregaende-skole',null,'Buskerud',null,'upper_secondary',null,'active'),
  ('eo-skole-ringerike-videregaende-skole','Ringerike videregående skole','ringerike-videregaende-skole',null,'Buskerud',null,'upper_secondary',null,'active'),
  ('eo-skole-st-hallvard-videregaende-skole','St. Hallvard videregående skole','st-hallvard-videregaende-skole',null,'Buskerud',null,'upper_secondary',null,'active'),
  ('eo-skole-vestfossen-ungdomsskole','Vestfossen ungdomsskole','vestfossen-ungdomsskole',null,'Buskerud',null,'lower_secondary',null,'active'),
  ('eo-skole-al-videregaende-skole','Ål videregående skole','al-videregaende-skole',null,'Buskerud',null,'upper_secondary',null,'active'),
  ('eo-skole-assiden-videregaende-skole','Åssiden videregående skole','assiden-videregaende-skole',null,'Buskerud',null,'upper_secondary',null,'active'),
  ('eo-skole-alta-videregaende-skole','Alta videregående skole','alta-videregaende-skole',null,'Finnmark',null,'upper_secondary',null,'active'),
  ('eo-skole-breilia-skole','Breilia Skole','breilia-skole',null,'Finnmark',null,'lower_secondary',null,'active'),
  ('eo-skole-batsfjord-private-videregaende-skole','Båtsfjord Private videregående skole','batsfjord-private-videregaende-skole',null,'Finnmark',null,'upper_secondary',null,'active'),
  ('eo-skole-batsfjord-skole','Båtsfjord skole','batsfjord-skole',null,'Finnmark',null,'lower_secondary',null,'active'),
  ('eo-skole-hammerfest-videregaende-skole','Hammerfest videregående skole','hammerfest-videregaende-skole',null,'Finnmark',null,'upper_secondary',null,'active'),
  ('eo-skole-honningsvag-skole','Honningsvåg skole','honningsvag-skole',null,'Finnmark',null,'lower_secondary',null,'active'),
  ('eo-skole-karasjok-skole','Karasjok skole','karasjok-skole',null,'Finnmark',null,'lower_secondary',null,'active'),
  ('eo-skole-kirkenes-videregaende-skole','Kirkenes videregående skole','kirkenes-videregaende-skole',null,'Finnmark',null,'upper_secondary',null,'active'),
  ('eo-skole-lakselv-videregaende-skole','Lakselv videregående skole','lakselv-videregaende-skole',null,'Finnmark',null,'upper_secondary',null,'active'),
  ('eo-skole-nordkapp-videregaende-skole','Nordkapp videregående skole','nordkapp-videregaende-skole',null,'Finnmark',null,'upper_secondary',null,'active'),
  ('eo-skole-samisk-videregaende-skole-avd-karasjok','Samisk videregående skole avd. Karasjok','samisk-videregaende-skole-avd-karasjok',null,'Finnmark',null,'upper_secondary',null,'active'),
  ('eo-skole-samisk-videregaende-skole-og-reindriftsskole-avd-kautokeino','Samisk videregående skole og reindriftsskole avd. Kautokeino','samisk-videregaende-skole-og-reindriftsskole-avd-kautokeino',null,'Finnmark',null,'upper_secondary',null,'active'),
  ('eo-skole-sandfallet-ungdomsskole','Sandfallet ungdomsskole','sandfallet-ungdomsskole',null,'Finnmark',null,'lower_secondary',null,'active'),
  ('eo-skole-sandnes-og-bjornevatn-skole','Sandnes og Bjørnevatn skole','sandnes-og-bjornevatn-skole',null,'Finnmark',null,'lower_secondary',null,'active'),
  ('eo-skole-tana-videregaende-skole','Tana videregående skole','tana-videregaende-skole',null,'Finnmark',null,'upper_secondary',null,'active'),
  ('eo-skole-vadso-videregaende-skole','Vadsø videregående skole','vadso-videregaende-skole',null,'Finnmark',null,'upper_secondary',null,'active'),
  ('eo-skole-vardo-videregaende-skole','Vardø videregående skole','vardo-videregaende-skole',null,'Finnmark',null,'upper_secondary',null,'active'),
  ('eo-skole-elverum-videregaende-skole','Elverum videregående skole','elverum-videregaende-skole',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-engerdal-barne-og-ungdomsskole','Engerdal barne- og ungdomsskole','engerdal-barne-og-ungdomsskole',null,'Innlandet',null,'lower_secondary',null,'active'),
  ('eo-skole-gausdal-videregaende-skole','Gausdal videregående skole','gausdal-videregaende-skole',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-gjovik-videregaende-skole','Gjøvik videregående skole','gjovik-videregaende-skole',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-hadeland-videregaende-skole','Hadeland videregående skole','hadeland-videregaende-skole',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-hamar-katedralskole','Hamar Katedralskole','hamar-katedralskole',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-jonsberg-videregaende-skole','Jønsberg videregående skole','jonsberg-videregaende-skole',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-kongsvinger-ungdomsskole','Kongsvinger ungdomsskole','kongsvinger-ungdomsskole',null,'Innlandet',null,'lower_secondary',null,'active'),
  ('eo-skole-lena-valle-videregaende-skole','Lena-Valle videregående skole','lena-valle-videregaende-skole',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-lillehammer-videregaende-skole-avd-nord','Lillehammer videregående skole, avd Nord','lillehammer-videregaende-skole-avd-nord',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-lillehammer-videregaende-skole-avd-sor','Lillehammer videregående skole, avd Sør','lillehammer-videregaende-skole-avd-sor',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-nord-gubransdalen-videregaende-skole-avd-dombas','Nord-Gubransdalen videregående skole, avd Dombås','nord-gubransdalen-videregaende-skole-avd-dombas',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-nord-gubransdalen-videregaende-skole-avd-lom','Nord-Gubransdalen videregående skole, avd Lom','nord-gubransdalen-videregaende-skole-avd-lom',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-nord-gubransdalen-videregaende-skole-avd-otta','Nord-Gubransdalen videregående skole, avd Otta','nord-gubransdalen-videregaende-skole-avd-otta',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-nord-osterdal-videregaende-skole','Nord-Østerdal videregående skole','nord-osterdal-videregaende-skole',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-otta-ungdomsskole','Otta ungdomsskole','otta-ungdomsskole',null,'Innlandet',null,'lower_secondary',null,'active'),
  ('eo-skole-raufoss-videregaende-skole','Raufoss videregående skole','raufoss-videregaende-skole',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-ringsaker-videregaende-skole','Ringsaker videregående skole','ringsaker-videregaende-skole',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-sentrum-videregaende-skole','Sentrum videregående skole','sentrum-videregaende-skole',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-solor-videregaende-skole-avd-flisa-klokkergarden-sonsterud-og-valer','Solør videregående skole (avd. Flisa, Klokkergården, Sønsterud og Våler)','solor-videregaende-skole-avd-flisa-klokkergarden-sonsterud-og-valer',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-stange-videregaende-skole','Stange videregående skole','stange-videregaende-skole',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-steinerskolen-pa-hedemarken','Steinerskolen på Hedemarken','steinerskolen-pa-hedemarken',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-storsteigen-videregaende-skole-avd-storsteigen-og-nordstumoen','Storsteigen videregående skole (avd Storsteigen og Nordstumoen)','storsteigen-videregaende-skole-avd-storsteigen-og-nordstumoen',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-trysil-videregaende-skole','Trysil videregående skole','trysil-videregaende-skole',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-valdres-vidaregaande-skule','Valdres vidaregåande skule','valdres-vidaregaande-skule',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-vinstra-vidaregaande-skule','Vinstra vidaregåande skule','vinstra-vidaregaande-skule',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-aretta-ungdomsskole','Åretta ungdomsskole','aretta-ungdomsskole',null,'Innlandet',null,'lower_secondary',null,'active'),
  ('eo-skole-asnes-ungdomsskole','Åsnes ungdomsskole','asnes-ungdomsskole',null,'Innlandet',null,'lower_secondary',null,'active'),
  ('eo-skole-ovrebyen-videregaende-skole','Øvrebyen videregående skole','ovrebyen-videregaende-skole',null,'Innlandet',null,'upper_secondary',null,'active'),
  ('eo-skole-atlanten-videregaende','Atlanten videregående','atlanten-videregaende',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-blindheim-ungdomsskole','Blindheim ungdomsskole','blindheim-ungdomsskole',null,'Møre og Romsdal',null,'lower_secondary',null,'active'),
  ('eo-skole-borgund-vidaregaande-skole','Borgund vidaregåande skole','borgund-vidaregaande-skole',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-gjermundnes-vidaregaande-skule','Gjermundnes vidaregåande skule','gjermundnes-vidaregaande-skule',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-haram-vidaregaande-skule','Haram vidaregåande skule','haram-vidaregaande-skule',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-hareid-ungdomskule','Hareid ungdomskule','hareid-ungdomskule',null,'Møre og Romsdal',null,'lower_secondary',null,'active'),
  ('eo-skole-hustadvika-videregaende-skole','Hustadvika videregående skole','hustadvika-videregaende-skole',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-kolvikbakken-ungdomsskole','Kolvikbakken ungdomsskole','kolvikbakken-ungdomsskole',null,'Møre og Romsdal',null,'lower_secondary',null,'active'),
  ('eo-skole-kristiansund-videregaende-skole','Kristiansund videregående skole','kristiansund-videregaende-skole',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-molde-videregaende-skole','Molde videregående skole','molde-videregaende-skole',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-myklebust-skule','Myklebust skule','myklebust-skule',null,'Møre og Romsdal',null,'lower_secondary',null,'active'),
  ('eo-skole-mandalen-skule','Måndalen skule','mandalen-skule',null,'Møre og Romsdal',null,'lower_secondary',null,'active'),
  ('eo-skole-rauma-videregaende-skole','Rauma Videregående skole','rauma-videregaende-skole',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-romsdal-videregaende-skole','Romsdal videregående skole','romsdal-videregaende-skole',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-skarbovik-ungdomsskole','Skarbøvik ungdomsskole','skarbovik-ungdomsskole',null,'Møre og Romsdal',null,'lower_secondary',null,'active'),
  ('eo-skole-spjelkavik-videregaende-skole','Spjelkavik videregående skole','spjelkavik-videregaende-skole',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-stranda-vidaregaande-skule','Stranda vidaregåande skule','stranda-vidaregaande-skule',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-sunndal-ungdomsskole','Sunndal ungdomsskole','sunndal-ungdomsskole',null,'Møre og Romsdal',null,'lower_secondary',null,'active'),
  ('eo-skole-sunndal-vidaregaande-skule','Sunndal vidaregåande skule','sunndal-vidaregaande-skule',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-surnadal-vidaregaande-skule','Surnadal vidaregåande skule','surnadal-vidaregaande-skule',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-sykkylven-vidaregaande-skule','Sykkylven vidaregåande skule','sykkylven-vidaregaande-skule',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-tingvoll-vidaregaande-skule','Tingvoll vidaregåande skule','tingvoll-vidaregaande-skule',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-ulstein-vidaregaande-skule','Ulstein vidaregåande skule','ulstein-vidaregaande-skule',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-volda-vidaregaande-skule','Volda vidaregåande skule','volda-vidaregaande-skule',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-afarnes-barne-og-ungdomsskole','Åfarnes barne- og ungdomsskole','afarnes-barne-og-ungdomsskole',null,'Møre og Romsdal',null,'lower_secondary',null,'active'),
  ('eo-skole-alesund-videregaende-skole-avd-fagerlia','Ålesund videregående skole, avd. Fagerlia','alesund-videregaende-skole-avd-fagerlia',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-alesund-videregaende-skole-avd-latinskolen','Ålesund videregående skole, avd. Latinskolen','alesund-videregaende-skole-avd-latinskolen',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-alesund-videregaende-skole-avd-volsdalsberga','Ålesund videregående skole, avd. Volsdalsberga','alesund-videregaende-skole-avd-volsdalsberga',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-orsta-vidaregaande-skule','Ørsta vidaregåande skule','orsta-vidaregaande-skule',null,'Møre og Romsdal',null,'upper_secondary',null,'active'),
  ('eo-skole-alstad-ungdomsskole','Alstad ungdomsskole','alstad-ungdomsskole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-andoy-videregaende-skole','Andøy videregående skole','andoy-videregaende-skole',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-aust-lofoten-videregaende-skole','Aust-Lofoten videregående skole','aust-lofoten-videregaende-skole',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-ballangen-skole','Ballangen skole','ballangen-skole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-bodin-videregaende-skole-og-maritime-fagskole','Bodin videregående skole og Maritime Fagskole','bodin-videregaende-skole-og-maritime-fagskole',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-bodo-videregaende-skole','Bodø videregående skole','bodo-videregaende-skole',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-bronnoysund-videregaende-skole','Brønnøysund videregående skole','bronnoysund-videregaende-skole',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-enga-skole','Enga skole','enga-skole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-fauske-videregaende-skole-avd-vestmyra','Fauske videregående skole, avd Vestmyra','fauske-videregaende-skole-avd-vestmyra',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-grane-barne-og-ungdomsskole','Grane barne- og ungdomsskole','grane-barne-og-ungdomsskole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-hadsel-videregaende-skole-avd-melbu','Hadsel videregående skole, avd Melbu','hadsel-videregaende-skole-avd-melbu',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-hadsel-videregaende-skole-avd-stokmarknes','Hadsel videregående skole, avd Stokmarknes','hadsel-videregaende-skole-avd-stokmarknes',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-hemnes-sentralskole','Hemnes Sentralskole','hemnes-sentralskole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-henningsvaer-skole','Henningsvær skole','henningsvaer-skole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-heroy-skole','Herøy skole','heroy-skole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-hilstad-barne-og-ungdomsskole','Hilstad barne- og ungdomsskole','hilstad-barne-og-ungdomsskole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-hunstad-ungdomsskole','Hunstad ungdomsskole','hunstad-ungdomsskole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-husoy-skole','Husøy skole','husoy-skole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-inndyr-skole','Inndyr skole','inndyr-skole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-kabelvag-ungdomsskole','Kabelvåg ungdomsskole','kabelvag-ungdomsskole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-kippermoen-ungdomsskole','Kippermoen Ungdomsskole','kippermoen-ungdomsskole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-knut-hamsun-videregaende-skole-avd-joarkkaskavlla-og-steigen','Knut Hamsun videregående skole (avd Joarkkaskåvllå og Steigen)','knut-hamsun-videregaende-skole-avd-joarkkaskavlla-og-steigen',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-korgen-sentralskole','Korgen Sentralskole','korgen-sentralskole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-kristen-videregaende-skole-nordland','Kristen videregående skole Nordland','kristen-videregaende-skole-nordland',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-lopsmark-skole','Løpsmark skole','lopsmark-skole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-melbu-skole','Melbu skole','melbu-skole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-meloy-videregaende-skole-avd-glomfjord-inndyr-og-ornes-ett-elevrad','Meløy videregående skole, avd Glomfjord, Inndyr og Ørnes. Ett elevråd.','meloy-videregaende-skole-avd-glomfjord-inndyr-og-ornes-ett-elevrad',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-mosjoen-videregaende-skole-tre-avdelinger-med-ett-elevrad','Mosjøen videregående skole Tre avdelinger med ett elevråd.','mosjoen-videregaende-skole-tre-avdelinger-med-ett-elevrad',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-narvik-videregaende-skole-avd-frydenlund','Narvik videregående skole, avd Frydenlund','narvik-videregaende-skole-avd-frydenlund',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-narvik-videregaende-skole-avd-oscarsborg','Narvik videregående skole, avd Oscarsborg','narvik-videregaende-skole-avd-oscarsborg',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-narvik-videregaende-skole-avd-solhaugen','Narvik videregående skole, avd Solhaugen','narvik-videregaende-skole-avd-solhaugen',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-polarsirkelen-videregaende-skole','Polarsirkelen videregående skole','polarsirkelen-videregaende-skole',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-saltdal-videregaende-skole','Saltdal videregående skole','saltdal-videregaende-skole',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-sandnessjoen-videregaende-skole','Sandnessjøen videregående skole','sandnessjoen-videregaende-skole',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-sortland-videregaende-skole-avd-sortland-og-kleiva','Sortland videregående skole, avd Sortland og Kleiva','sortland-videregaende-skole-avd-sortland-og-kleiva',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-sortland-videregaende-skole-avd-oksnes','Sortland videregående skole, avd Øksnes','sortland-videregaende-skole-avd-oksnes',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-svolvaer-skole','Svolvær skole','svolvaer-skole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-tverlandet-skole','Tverlandet skole','tverlandet-skole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-utskarpen-barne-og-ungdomsskole','Utskarpen barne- og ungdomsskole','utskarpen-barne-og-ungdomsskole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-vega-barne-og-ungdomsskole','Vega barne- og ungdomsskole','vega-barne-og-ungdomsskole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-vest-lofoten-videregaende-skole','Vest-Lofoten videregående skole','vest-lofoten-videregaende-skole',null,'Nordland',null,'upper_secondary',null,'active'),
  ('eo-skole-ornes-skole','Ørnes skole','ornes-skole',null,'Nordland',null,'lower_secondary',null,'active'),
  ('eo-skole-apallokka-skole','Apalløkka skole','apallokka-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-bjornholt-ungdomsskole','Bjørnholt ungdomsskole','bjornholt-ungdomsskole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-bjornholt-videregaende-skole','Bjørnholt videregående skole','bjornholt-videregaende-skole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-blindern-videregaende-skole','Blindern videregående skole','blindern-videregaende-skole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-brannfjell-skole','Brannfjell skole','brannfjell-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-boler-skole','Bøler skole','boler-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-edvard-munch-videregaende-skole','Edvard Munch videregående skole','edvard-munch-videregaende-skole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-ellingsrud-skole','Ellingsrud skole','ellingsrud-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-elvebakken-videregaende-skole','Elvebakken videregående skole','elvebakken-videregaende-skole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-etterstad-videregaende-skole','Etterstad videregående skole','etterstad-videregaende-skole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-fagerborg-skole','Fagerborg skole','fagerborg-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-foss-videregaende-skole','Foss videregående skole','foss-videregaende-skole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-frydenberg-skole','Frydenberg skole','frydenberg-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-fyrstikkalleen-skole-ungdomsskole','Fyrstikkalleén skole, ungdomsskole','fyrstikkalleen-skole-ungdomsskole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-fyrstikkalleen-skole-videregaende-skole','Fyrstikkalleén skole, videregående skole','fyrstikkalleen-skole-videregaende-skole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-groruddalen','Groruddalen','groruddalen',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-hartvig-nissens-videregaende-skole','Hartvig Nissens videregående skole','hartvig-nissens-videregaende-skole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-haugerud-skole','Haugerud skole','haugerud-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-hauketo-skole','Hauketo skole','hauketo-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-hellerud-videregaende-skole','Hellerud videregående skole','hellerud-videregaende-skole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-heltberg-private-gymnas-ulleval','Heltberg Private Gymnas (Ullevål)','heltberg-private-gymnas-ulleval',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-hersleb-videregaende-skole','Hersleb videregående skole','hersleb-videregaende-skole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-holmlia-skole','Holmlia skole','holmlia-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-hovseter-skole','Hovseter skole','hovseter-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-jordal-skole','Jordal skole','jordal-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-kongsskogen-videregaende-skole','Kongsskogen videregående skole','kongsskogen-videregaende-skole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-kuben-videregaende-skole','Kuben videregående skole','kuben-videregaende-skole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-lambertseter-grunnskole','Lambertseter grunnskole','lambertseter-grunnskole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-lambertseter-videregaende-skole','Lambertseter videregående skole','lambertseter-videregaende-skole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-lofsrud-skole','Lofsrud skole','lofsrud-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-marienlyst-skole','Marienlyst skole','marienlyst-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-midtstuen-skole','Midtstuen skole','midtstuen-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-natur-videregaende-skole','Natur videregående skole','natur-videregaende-skole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-nordberg-skole','Nordberg skole','nordberg-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-nydalen-videregaende-skole','Nydalen videregående skole','nydalen-videregaende-skole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-nyskolen-i-oslo','Nyskolen i Oslo','nyskolen-i-oslo',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-oppsal-skole','Oppsal skole','oppsal-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-oslo-by-steinerskole','Oslo By Steinerskole','oslo-by-steinerskole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-oslo-katedralskole','Oslo Katedralskole','oslo-katedralskole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-persbraten-videregaende-skole','Persbråten videregående skole','persbraten-videregaende-skole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-ris-skole','Ris skole','ris-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-rudolf-steinerskolen-i-oslo','Rudolf Steinerskolen i Oslo','rudolf-steinerskolen-i-oslo',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-ruselokka-skole','Ruseløkka skole','ruselokka-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-sagene-skole','Sagene skole','sagene-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-skullerud-skole','Skullerud skole','skullerud-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-skoyenasen-skole','Skøyenåsen skole','skoyenasen-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-sofienberg-skole','Sofienberg skole','sofienberg-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-sollerudstranda-skole','Sollerudstranda skole','sollerudstranda-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-st-sunniva-skole','St. Sunniva skole','st-sunniva-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-stasjonsfjellet-skole','Stasjonsfjellet skole','stasjonsfjellet-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-stiftelsen-den-tyske-skoleforening-i-norge','Stiftelsen Den Tyske Skoleforening i Norge','stiftelsen-den-tyske-skoleforening-i-norge',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-stovner-videregaende-skole','Stovner videregående skole','stovner-videregaende-skole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-ullern-videregaende-skole','Ullern videregående skole','ullern-videregaende-skole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-ulsrud-videregaende-skole','Ulsrud videregående skole','ulsrud-videregaende-skole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-vika-videregaende-skole','Vika videregående skole','vika-videregaende-skole',null,'Oslo',null,'upper_secondary',null,'active'),
  ('eo-skole-oraker-skole','Øraker skole','oraker-skole',null,'Oslo',null,'lower_secondary',null,'active'),
  ('eo-skole-akademiet-videregaende-skole-sandes','Akademiet Videregående skole Sandes','akademiet-videregaende-skole-sandes',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-bergeland-videregaende-skole','Bergeland videregående skole','bergeland-videregaende-skole',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-bokn-skule','Bokn skule','bokn-skule',null,'Rogaland',null,'lower_secondary',null,'active'),
  ('eo-skole-bryne-videregaende-skole','Bryne videregående skole','bryne-videregaende-skole',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-dalane-videregaende-skole','Dalane videregående skole','dalane-videregaende-skole',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-forsand-skule','Forsand skule','forsand-skule',null,'Rogaland',null,'lower_secondary',null,'active'),
  ('eo-skole-godalen-videregaende-skole','Godalen videregående skole','godalen-videregaende-skole',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-haugaland-videregaende-skole','Haugaland videregående skole','haugaland-videregaende-skole',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-hetland-videregaende-skole','Hetland videregående skole','hetland-videregaende-skole',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-hjelmeland-skule','Hjelmeland skule','hjelmeland-skule',null,'Rogaland',null,'lower_secondary',null,'active'),
  ('eo-skole-jatta-videregaende-skole','Jåttå videregående skole','jatta-videregaende-skole',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-kopervik-videregaende-skole','Kopervik videregående skole','kopervik-videregaende-skole',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-randaberg-videregaende-skole','Randaberg videregående skole','randaberg-videregaende-skole',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-sandnes-videregaende-skole','Sandnes videregående skole','sandnes-videregaende-skole',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-sauda-videregaende-skole-avd-birkeland-hovudskulen-og-sand','Sauda videregående skole (avd Birkeland, Hovudskulen og Sand)','sauda-videregaende-skole-avd-birkeland-hovudskulen-og-sand',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-skeisvang-vgs','Skeisvang VGS','skeisvang-vgs',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-skoleskipet-gann','Skoleskipet Gann','skoleskipet-gann',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-st-olav-videregaende-skole','St Olav videregående skole','st-olav-videregaende-skole',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-stavanger-katedralskole','Stavanger katedralskole','stavanger-katedralskole',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-strand-videregaende-skole','Strand videregående skole','strand-videregaende-skole',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-vardafjell-videregaende-skole','Vardafjell videregående skole','vardafjell-videregaende-skole',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-vagen-videregaende-skole','Vågen videregående skole','vagen-videregaende-skole',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-oksnevad-videregaende-skole','Øksnevad videregående skole','oksnevad-videregaende-skole',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-olen-videregaende-skole','Ølen videregående skole','olen-videregaende-skole',null,'Rogaland',null,'upper_secondary',null,'active'),
  ('eo-skole-oygard-ungdomsskole','Øygard ungdomsskole','oygard-ungdomsskole',null,'Rogaland',null,'lower_secondary',null,'active'),
  ('eo-skole-bamble-videregaende-skole','Bamble videregående skole','bamble-videregaende-skole',null,'Telemark',null,'upper_secondary',null,'active'),
  ('eo-skole-bamble-videregaende-skole-avd-croftholmen-og-grasmyr','Bamble videregående skole (avd. Croftholmen og Grasmyr)','bamble-videregaende-skole-avd-croftholmen-og-grasmyr',null,'Telemark',null,'upper_secondary',null,'active'),
  ('eo-skole-bo-ungdomsskule','Bø ungdomsskule','bo-ungdomsskule',null,'Telemark',null,'lower_secondary',null,'active'),
  ('eo-skole-bo-videregaande-skule','Bø videregåande skule','bo-videregaande-skule',null,'Telemark',null,'upper_secondary',null,'active'),
  ('eo-skole-hjalmar-johansen-videregaende-skole','Hjalmar Johansen videregående skole','hjalmar-johansen-videregaende-skole',null,'Telemark',null,'upper_secondary',null,'active'),
  ('eo-skole-kragero-videregaende-skole','Kragerø videregående skole','kragero-videregaende-skole',null,'Telemark',null,'upper_secondary',null,'active'),
  ('eo-skole-maela-ungdomsskole','Mæla ungdomsskole','maela-ungdomsskole',null,'Telemark',null,'lower_secondary',null,'active'),
  ('eo-skole-nome-videregaende-skole-avd-lunde','Nome videregående skole, avd Lunde','nome-videregaende-skole-avd-lunde',null,'Telemark',null,'upper_secondary',null,'active'),
  ('eo-skole-nome-videregaende-skole-avd-sove','Nome videregående skole, avd Søve','nome-videregaende-skole-avd-sove',null,'Telemark',null,'upper_secondary',null,'active'),
  ('eo-skole-notodden-videregaende-skole','Notodden videregående skole','notodden-videregaende-skole',null,'Telemark',null,'upper_secondary',null,'active'),
  ('eo-skole-rjukan-videregaende-skole','Rjukan videregående skole','rjukan-videregaende-skole',null,'Telemark',null,'upper_secondary',null,'active'),
  ('eo-skole-skien-videregaende-skole','Skien videregående skole','skien-videregaende-skole',null,'Telemark',null,'upper_secondary',null,'active'),
  ('eo-skole-stiftelsen-toppidrettsgymnaset-i-telemark','Stiftelsen Toppidrettsgymnaset i Telemark','stiftelsen-toppidrettsgymnaset-i-telemark',null,'Telemark',null,'upper_secondary',null,'active'),
  ('eo-skole-telemark-toppidrett-ungdomsskole-skien','Telemark Toppidrett Ungdomsskole Skien','telemark-toppidrett-ungdomsskole-skien',null,'Telemark',null,'lower_secondary',null,'active'),
  ('eo-skole-vest-telemark-videregaende-skole-avd-dalen-og-seljord','Vest-Telemark videregående skole, avd Dalen og Seljord','vest-telemark-videregaende-skole-avd-dalen-og-seljord',null,'Telemark',null,'upper_secondary',null,'active'),
  ('eo-skole-bardu-ungdomsskole','Bardu ungdomsskole','bardu-ungdomsskole',null,'Troms',null,'lower_secondary',null,'active'),
  ('eo-skole-bardufoss-hogtun-videregaende-skole-avd-bardufoss-og-hogtun','Bardufoss Høgtun videregående skole (avd Bardufoss og Høgtun)','bardufoss-hogtun-videregaende-skole-avd-bardufoss-og-hogtun',null,'Troms',null,'upper_secondary',null,'active'),
  ('eo-skole-bardufoss-ungdomsskole','Bardufoss ungdomsskole','bardufoss-ungdomsskole',null,'Troms',null,'lower_secondary',null,'active'),
  ('eo-skole-botnhamn-skole','Botnhamn skole','botnhamn-skole',null,'Troms',null,'lower_secondary',null,'active'),
  ('eo-skole-breivang-videregaende-skole','Breivang videregående skole','breivang-videregaende-skole',null,'Troms',null,'upper_secondary',null,'active'),
  ('eo-skole-finnsnes-ungdomsskole','Finnsnes ungdomsskole','finnsnes-ungdomsskole',null,'Troms',null,'lower_secondary',null,'active'),
  ('eo-skole-gibostad-barne-og-ungdomsskole','Gibostad barne- og ungdomsskole','gibostad-barne-og-ungdomsskole',null,'Troms',null,'lower_secondary',null,'active'),
  ('eo-skole-hagebyen-skole','Hagebyen skole','hagebyen-skole',null,'Troms',null,'lower_secondary',null,'active'),
  ('eo-skole-hansnes-barne-og-ungdomsskole','Hansnes barne- og ungdomsskole','hansnes-barne-og-ungdomsskole',null,'Troms',null,'lower_secondary',null,'active'),
  ('eo-skole-heggen-videregaende-skole','Heggen videregående skole','heggen-videregaende-skole',null,'Troms',null,'upper_secondary',null,'active'),
  ('eo-skole-hillesoyskolen-brensholmen-skole','Hillesøyskolen - Brensholmen skole','hillesoyskolen-brensholmen-skole',null,'Troms',null,'lower_secondary',null,'active'),
  ('eo-skole-ishavsbyen-videregaende-skole','Ishavsbyen videregående skole','ishavsbyen-videregaende-skole',null,'Troms',null,'upper_secondary',null,'active'),
  ('eo-skole-kongsbakken-videregaende-skole','Kongsbakken videregående skole','kongsbakken-videregaende-skole',null,'Troms',null,'upper_secondary',null,'active'),
  ('eo-skole-kvaloya-videregaende-skole','Kvaløya videregående skole','kvaloya-videregaende-skole',null,'Troms',null,'upper_secondary',null,'active'),
  ('eo-skole-lavangen-skole','Lavangen skole','lavangen-skole',null,'Troms',null,'lower_secondary',null,'active'),
  ('eo-skole-longyearbyen-skole-grunnskole','Longyearbyen skole, grunnskole','longyearbyen-skole-grunnskole',null,'Troms',null,'lower_secondary',null,'active'),
  ('eo-skole-longyearbyen-skole-videregaende-skole','Longyearbyen skole, videregående skole','longyearbyen-skole-videregaende-skole',null,'Troms',null,'upper_secondary',null,'active'),
  ('eo-skole-malangen-skole','Malangen skole','malangen-skole',null,'Troms',null,'lower_secondary',null,'active'),
  ('eo-skole-manndalen-skole','Manndalen skole','manndalen-skole',null,'Troms',null,'lower_secondary',null,'active'),
  ('eo-skole-nord-troms-videregaende-skole-avd-nordreisa-og-skjervoy','Nord-Troms videregående skole (avd. Nordreisa og Skjervøy)','nord-troms-videregaende-skole-avd-nordreisa-og-skjervoy',null,'Troms',null,'upper_secondary',null,'active'),
  ('eo-skole-nordborg-videregaende-skole','Nordborg videregående skole','nordborg-videregaende-skole',null,'Troms',null,'upper_secondary',null,'active'),
  ('eo-skole-nordkjosbotn-videregaende-skole','Nordkjosbotn videregående skole','nordkjosbotn-videregaende-skole',null,'Troms',null,'upper_secondary',null,'active'),
  ('eo-skole-salangen-skole','Salangen skole','salangen-skole',null,'Troms',null,'upper_secondary',null,'active'),
  ('eo-skole-sand-skole','Sand skole','sand-skole',null,'Troms',null,'lower_secondary',null,'active'),
  ('eo-skole-seljestad-ungdomskole','Seljestad Ungdomskole','seljestad-ungdomskole',null,'Troms',null,'lower_secondary',null,'active'),
  ('eo-skole-senja-videregaende-skole-avd-finnfjordbotn','Senja videregående skole, avd. Finnfjordbotn','senja-videregaende-skole-avd-finnfjordbotn',null,'Troms',null,'lower_secondary',null,'active'),
  ('eo-skole-senja-videregaende-skole-avd-gibostad','Senja videregående skole, avd. Gibostad','senja-videregaende-skole-avd-gibostad',null,'Troms',null,'lower_secondary',null,'active'),
  ('eo-skole-sjovegan-videregaende-skole','Sjøvegan videregående skole','sjovegan-videregaende-skole',null,'Troms',null,'lower_secondary',null,'active'),
  ('eo-skole-sommerlyst-skole','Sommerlyst skole','sommerlyst-skole',null,'Troms',null,'lower_secondary',null,'active'),
  ('eo-skole-stangnes-ra-videregaende-skole','Stangnes Rå videregående skole','stangnes-ra-videregaende-skole',null,'Troms',null,'upper_secondary',null,'active'),
  ('eo-skole-sorreisa-sentralskole','Sørreisa sentralskole','sorreisa-sentralskole',null,'Troms',null,'lower_secondary',null,'active'),
  ('eo-skole-tromsdalen-videregaende-skole','Tromsdalen videregående skole','tromsdalen-videregaende-skole',null,'Troms',null,'upper_secondary',null,'active'),
  ('eo-skole-tromstun-skole','Tromstun skole','tromstun-skole',null,'Troms',null,'upper_secondary',null,'active'),
  ('eo-skole-aglo-videregaende-skole','Aglo videregående skole','aglo-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-bybroen-videregaende-skole-as','Bybroen videregående skole AS','bybroen-videregaende-skole-as',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-byasen-videregaende-skole','Byåsen videregående skole','byasen-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-charlottenlund-ungdomsskole','Charlottenlund ungdomsskole','charlottenlund-ungdomsskole',null,'Trøndelag',null,'lower_secondary',null,'active'),
  ('eo-skole-charlottenlund-videregaende-skole','Charlottenlund videregående skole','charlottenlund-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-fosen-videregaende-skole','Fosen videregående skole','fosen-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-gauldal-videregaende-skole','Gauldal videregående skole','gauldal-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-grong-ungdomsskole','Grong Ungdomsskole','grong-ungdomsskole',null,'Trøndelag',null,'lower_secondary',null,'active'),
  ('eo-skole-grong-videregaende-skole','Grong videregående skole','grong-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-guri-kunna-videregaende-skole-avd-froya-og-hitra','Guri Kunna videregående skole (avd. Frøya og Hitra)','guri-kunna-videregaende-skole-avd-froya-og-hitra',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-halsen-ungdomsskole','Halsen ungdomsskole','halsen-ungdomsskole',null,'Trøndelag',null,'lower_secondary',null,'active'),
  ('eo-skole-heimdal-videregaende-skole','Heimdal videregående skole','heimdal-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-inderoy-videregaende-skole','Inderøy videregående skole','inderoy-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-johan-bojer-videregaende-skole','Johan Bojer videregående skole','johan-bojer-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-kyrksaeterora-videregaende-skole','Kyrksæterøra videregående skole','kyrksaeterora-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-lauvsnes-skole','Lauvsnes skole','lauvsnes-skole',null,'Trøndelag',null,'lower_secondary',null,'active'),
  ('eo-skole-levanger-videregaende-skole','Levanger videregående skole','levanger-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-malvik-videregaende-skole','Malvik videregående skole','malvik-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-meldal-videregaende-skole','Meldal videregående skole','meldal-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-melhus-videregaende-skole','Melhus videregående skole','melhus-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-meraker-videregaende-skole','Meråker videregående skole','meraker-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-maere-landbruksskole','Mære landbruksskole','maere-landbruksskole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-olav-duun-videregaende-skole','Olav Duun videregående skole','olav-duun-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-ole-vig-videregaende-skole','Ole Vig videregående skole','ole-vig-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-oppdal-videregaende-skole','Oppdal videregående skole','oppdal-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-orkdal-videregaende-skole','Orkdal videregående skole','orkdal-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-roros-videregaende-skole','Røros videregående skole','roros-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-skjetlein-videregaende-skole','Skjetlein videregående skole','skjetlein-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-steinerskolen-i-trondheim-grunnskole','Steinerskolen i Trondheim, grunnskole','steinerskolen-i-trondheim-grunnskole',null,'Trøndelag',null,'lower_secondary',null,'active'),
  ('eo-skole-steinerskolen-pa-rotvoll','Steinerskolen på Rotvoll','steinerskolen-pa-rotvoll',null,'Trøndelag',null,'lower_secondary',null,'active'),
  ('eo-skole-steinkjer-montessoriskole','Steinkjer montessoriskole','steinkjer-montessoriskole',null,'Trøndelag',null,'lower_secondary',null,'active'),
  ('eo-skole-steinkjer-videregaende-skole','Steinkjer videregående skole','steinkjer-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-strinda-videregaende-skole','Strinda videregående skole','strinda-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-thora-storm-videregaende-skole','Thora Storm videregående skole','thora-storm-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-tiller-videregaende-skole','Tiller videregående skole','tiller-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-trondheim-international-school','Trondheim International School','trondheim-international-school',null,'Trøndelag',null,'lower_secondary',null,'active'),
  ('eo-skole-trondheim-katedralskole','Trondheim Katedralskole','trondheim-katedralskole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-verdal-videregaende-skole','Verdal videregående skole','verdal-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-vikhammer-ungdomsskole','Vikhammer ungdomsskole','vikhammer-ungdomsskole',null,'Trøndelag',null,'lower_secondary',null,'active'),
  ('eo-skole-ytre-namdal-videregaende-skole','Ytre Namdal videregående skole','ytre-namdal-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-afjord-videregaende-skole','Åfjord videregående skole','afjord-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-arlivoll-skole','Årlivoll skole','arlivoll-skole',null,'Trøndelag',null,'lower_secondary',null,'active'),
  ('eo-skole-oya-videregaende-skole','Øya videregående skole','oya-videregaende-skole',null,'Trøndelag',null,'upper_secondary',null,'active'),
  ('eo-skole-faerder-videregaende-skole','Færder videregående skole','faerder-videregaende-skole',null,'Vestfold',null,'upper_secondary',null,'active'),
  ('eo-skole-greveskogen-videregaende-skole','Greveskogen videregående skole','greveskogen-videregaende-skole',null,'Vestfold',null,'upper_secondary',null,'active'),
  ('eo-skole-holmestrand-videregaende-skole','Holmestrand videregående skole','holmestrand-videregaende-skole',null,'Vestfold',null,'upper_secondary',null,'active'),
  ('eo-skole-notteroy-videregaende-skole','Nøtterøy videregående skole','notteroy-videregaende-skole',null,'Vestfold',null,'upper_secondary',null,'active'),
  ('eo-skole-revetal-ungdomsskole','Revetal ungdomsskole','revetal-ungdomsskole',null,'Vestfold',null,'lower_secondary',null,'active'),
  ('eo-skole-sande-videregaende-skole','Sande Videregående skole','sande-videregaende-skole',null,'Vestfold',null,'upper_secondary',null,'active'),
  ('eo-skole-steinerskolen-i-vestfold-grunnskolen-pa-notteroy','Steinerskolen i Vestfold - Grunnskolen på Nøtterøy','steinerskolen-i-vestfold-grunnskolen-pa-notteroy',null,'Vestfold',null,'lower_secondary',null,'active'),
  ('eo-skole-steinerskolen-i-vestfold-slottsfjellet-videregaende','Steinerskolen i Vestfold - Slottsfjellet videregående','steinerskolen-i-vestfold-slottsfjellet-videregaende',null,'Vestfold',null,'upper_secondary',null,'active'),
  ('eo-skole-teigar-ungdomsskole','Teigar ungdomsskole','teigar-ungdomsskole',null,'Vestfold',null,'lower_secondary',null,'active'),
  ('eo-skole-tjodalyng-skole','Tjodalyng skole','tjodalyng-skole',null,'Vestfold',null,'lower_secondary',null,'active'),
  ('eo-skole-amalie-skram-videregaende-skole','Amalie Skram videregående skole','amalie-skram-videregaende-skole',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-arna-vidaregaande-skule','Arna vidaregåande skule','arna-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-askvoll-skule','Askvoll skule','askvoll-skule',null,'Vestland',null,'lower_secondary',null,'active'),
  ('eo-skole-askoy-videregaende-skole','Askøy videregående skole','askoy-videregaende-skole',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-austevoll-vidaregaande-skule','Austevoll vidaregåande skule','austevoll-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-austrheim-vidaregaande-skule','Austrheim vidaregåande skule','austrheim-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-bergen-katedralskole','Bergen katedralskole','bergen-katedralskole',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-bergen-katedralskole-avd-kyrre','Bergen katedralskole, avd Kyrre','bergen-katedralskole-avd-kyrre',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-bomlo-vidaregaande-skule','Bømlo vidaregåande skule','bomlo-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-dale-vidaregaande-skule','Dale vidaregåande skule','dale-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-eid-vidaregaande-skule','Eid vidaregåande skule','eid-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-firda-vidaregaande-skule','Firda vidaregåande skule','firda-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-flora-vidaregaande-skule','Flora vidaregåande skule','flora-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-fusa-vidaregaande-skule','Fusa vidaregåande skule','fusa-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-fyllingsdalen-videregaende-skole','Fyllingsdalen videregående skole','fyllingsdalen-videregaende-skole',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-forde-ungdomsskule','Førde ungdomsskule','forde-ungdomsskule',null,'Vestland',null,'lower_secondary',null,'active'),
  ('eo-skole-forde-vgs','Førde vgs','forde-vgs',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-granvin-ungdomsskole','Granvin ungdomsskole','granvin-ungdomsskole',null,'Vestland',null,'lower_secondary',null,'active'),
  ('eo-skole-halbrend-skule','Halbrend skule','halbrend-skule',null,'Vestland',null,'lower_secondary',null,'active'),
  ('eo-skole-hauso-barne-og-ungdomsskule','Hauso barne- og ungdomsskule','hauso-barne-og-ungdomsskule',null,'Vestland',null,'lower_secondary',null,'active'),
  ('eo-skole-hoyanger-vidaregaande-skule','Høyanger vidaregåande skule','hoyanger-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-kjokkelvik-skole','Kjøkkelvik skole','kjokkelvik-skole',null,'Vestland',null,'lower_secondary',null,'active'),
  ('eo-skole-knarvik-vidaregaande-skule','Knarvik vidaregåande skule','knarvik-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-krokeide-videregaende-skole','Krokeide videregående skole','krokeide-videregaende-skole',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-kvam-ungdomsskole','Kvam ungdomsskole','kvam-ungdomsskole',null,'Vestland',null,'lower_secondary',null,'active'),
  ('eo-skole-kvam-vidaregaande-skule','Kvam vidaregåande skule','kvam-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-kyrkjekrinsen-skole','Kyrkjekrinsen skole','kyrkjekrinsen-skole',null,'Vestland',null,'lower_secondary',null,'active'),
  ('eo-skole-laksevag-og-bergen-maritime-videregaende-skole','Laksevåg og Bergen maritime videregående skole','laksevag-og-bergen-maritime-videregaende-skole',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-langhaugen-videregaende-skole','Langhaugen videregående skole','langhaugen-videregaende-skole',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-metis-videregaende-skole-as','Metis videregående skole AS','metis-videregaende-skole-as',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-maloy-vidaregaande-skule','Måløy vidaregåande skule','maloy-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-nordahl-grieg-videregaende-skole','Nordahl Grieg videregående skole','nordahl-grieg-videregaende-skole',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-odda-vidaregaande-skule','Odda vidaregåande skule','odda-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-olsvikasen-videregaende-skole','Olsvikåsen videregående skole','olsvikasen-videregaende-skole',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-os-gymnas','Os gymnas','os-gymnas',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-os-vidaregaande-skule','Os vidaregåande skule','os-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-osteroy-vidaregaande-skule','Osterøy vidaregåande skule','osteroy-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-sandsli-videregende-skole','Sandsli Videregende skole','sandsli-videregende-skole',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-slatthaug-vidaregaande-skule','Slåtthaug vidaregåande skule','slatthaug-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-sogndal-vidaregaande-skule','Sogndal vidaregåande skule','sogndal-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-sotra-vidaregaande-skule-avd-bildoy','Sotra vidaregåande skule, avd Bildøy','sotra-vidaregaande-skule-avd-bildoy',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-sotra-vidaregaande-skule-avd-sund','Sotra vidaregåande skule, avd Sund','sotra-vidaregaande-skule-avd-sund',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-stend-videregaende-skole-naturbrukskolene','Stend videregående skole (Naturbrukskolene)','stend-videregaende-skole-naturbrukskolene',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-stord-vidaregaande-skule','Stord vidaregåande skule','stord-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-strandebarm-skule','Strandebarm Skule','strandebarm-skule',null,'Vestland',null,'lower_secondary',null,'active'),
  ('eo-skole-stryn-vidaregaande-skule','Stryn vidaregåande skule','stryn-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-sund-ungdomsskole','Sund ungdomsskole','sund-ungdomsskole',null,'Vestland',null,'lower_secondary',null,'active'),
  ('eo-skole-tertnes-videregaende-skole','Tertnes videregående skole','tertnes-videregaende-skole',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-uwc-red-cross-nordic','UWC Red Cross Nordic','uwc-red-cross-nordic',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-voss-gymnas','Voss gymnas','voss-gymnas',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-voss-videregaende-skole','Voss videregående skole','voss-videregaende-skole',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-ardal-vidaregaande-skule','Årdal vidaregåande skule','ardal-vidaregaande-skule',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-arstad-videregaende-skole','Årstad videregående skole','arstad-videregaende-skole',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-asane-videregaende-skole','Åsane videregående skole','asane-videregaende-skole',null,'Vestland',null,'upper_secondary',null,'active'),
  ('eo-skole-akademiet-fredrikstad-as','Akademiet Fredrikstad AS','akademiet-fredrikstad-as',null,'Østfold',null,'upper_secondary',null,'active'),
  ('eo-skole-askim-ungdomsskole','Askim ungdomsskole','askim-ungdomsskole',null,'Østfold',null,'lower_secondary',null,'active'),
  ('eo-skole-askim-videregaende-skole','Askim videregående skole','askim-videregaende-skole',null,'Østfold',null,'upper_secondary',null,'active'),
  ('eo-skole-borg-videregaende-skole','Borg videregående skole','borg-videregaende-skole',null,'Østfold',null,'upper_secondary',null,'active'),
  ('eo-skole-borge-ungdomsskole','Borge ungdomsskole','borge-ungdomsskole',null,'Østfold',null,'lower_secondary',null,'active'),
  ('eo-skole-frederik-ii-videregaende-skole','Frederik II videregående skole','frederik-ii-videregaende-skole',null,'Østfold',null,'upper_secondary',null,'active'),
  ('eo-skole-glemmen-videregaende-skole','Glemmen videregående skole','glemmen-videregaende-skole',null,'Østfold',null,'upper_secondary',null,'active'),
  ('eo-skole-gressvik-ungdomsskole','Gressvik ungdomsskole','gressvik-ungdomsskole',null,'Østfold',null,'lower_secondary',null,'active'),
  ('eo-skole-greaker-videregaende-skole','Greåker videregående skole','greaker-videregaende-skole',null,'Østfold',null,'upper_secondary',null,'active'),
  ('eo-skole-halden-videregaende-skole','Halden videregående skole','halden-videregaende-skole',null,'Østfold',null,'upper_secondary',null,'active'),
  ('eo-skole-haugeasen-ungdomsskole','Haugeåsen ungdomsskole','haugeasen-ungdomsskole',null,'Østfold',null,'lower_secondary',null,'active'),
  ('eo-skole-hvaler-barne-og-ungdomsskole','Hvaler barne og ungdomsskole','hvaler-barne-og-ungdomsskole',null,'Østfold',null,'lower_secondary',null,'active'),
  ('eo-skole-kalnes-videregaende-skole','Kalnes videregående skole','kalnes-videregaende-skole',null,'Østfold',null,'upper_secondary',null,'active'),
  ('eo-skole-kirkebygden-ungdomsskole-valer','Kirkebygden ungdomsskole (Våler)','kirkebygden-ungdomsskole-valer',null,'Østfold',null,'upper_secondary',null,'active'),
  ('eo-skole-kirkeparken-videregaende-skole','Kirkeparken videregående skole','kirkeparken-videregaende-skole',null,'Østfold',null,'lower_secondary',null,'active'),
  ('eo-skole-knapstad-barne-og-ungdomsskole','Knapstad Barne- og Ungdomsskole','knapstad-barne-og-ungdomsskole',null,'Østfold',null,'lower_secondary',null,'active'),
  ('eo-skole-krakeroy-ungdomsskole','Kråkerøy ungdomsskole','krakeroy-ungdomsskole',null,'Østfold',null,'lower_secondary',null,'active'),
  ('eo-skole-kvernhuset-ungdomsskole','Kvernhuset Ungdomsskole','kvernhuset-ungdomsskole',null,'Østfold',null,'lower_secondary',null,'active'),
  ('eo-skole-malakoff-videregaende-skole','Malakoff videregående skole','malakoff-videregaende-skole',null,'Østfold',null,'upper_secondary',null,'active'),
  ('eo-skole-mysen-ungdomsskole','Mysen ungdomsskole','mysen-ungdomsskole',null,'Østfold',null,'upper_secondary',null,'active'),
  ('eo-skole-mysen-videregaende-skole','Mysen videregående skole','mysen-videregaende-skole',null,'Østfold',null,'upper_secondary',null,'active'),
  ('eo-skole-rodsberg-ungdomsskole','Rødsberg ungdomsskole','rodsberg-ungdomsskole',null,'Østfold',null,'lower_secondary',null,'active'),
  ('eo-skole-spydeberg-ungdomsskole','Spydeberg ungdomsskole','spydeberg-ungdomsskole',null,'Østfold',null,'lower_secondary',null,'active'),
  ('eo-skole-st-olav-videregaende-skole-sarpsborg','St. Olav videregående skole - Sarpsborg','st-olav-videregaende-skole-sarpsborg',null,'Østfold',null,'upper_secondary',null,'active'),
  ('eo-skole-steinerskolen-i-fredrikstad','Steinerskolen i Fredrikstad','steinerskolen-i-fredrikstad',null,'Østfold',null,'lower_secondary',null,'active'),
  ('eo-skole-steinerskolen-i-moss-grunnskole','Steinerskolen i Moss, grunnskole','steinerskolen-i-moss-grunnskole',null,'Østfold',null,'lower_secondary',null,'active'),
  ('eo-skole-steinerskolen-i-moss-videregaende-skole','Steinerskolen i Moss, videregående skole','steinerskolen-i-moss-videregaende-skole',null,'Østfold',null,'upper_secondary',null,'active'),
  ('eo-skole-stiftelsen-steinerskolen-i-indre-ostfold-askim','Stiftelsen Steinerskolen i Indre Østfold (Askim)','stiftelsen-steinerskolen-i-indre-ostfold-askim',null,'Østfold',null,'lower_secondary',null,'active'),
  ('eo-skole-tindlund-ungdomsskole','Tindlund ungdomsskole','tindlund-ungdomsskole',null,'Østfold',null,'lower_secondary',null,'active'),
  ('eo-skole-trogstad-ungdomsskole','Trøgstad Ungdomsskole','trogstad-ungdomsskole',null,'Østfold',null,'lower_secondary',null,'active'),
  ('eo-skole-vestbygda-ungdomsskole','Vestbygda ungdomsskole','vestbygda-ungdomsskole',null,'Østfold',null,'lower_secondary',null,'active')
) as v(external_id,name,slug,organization_number,county,local_board,school_level,contact_email,status)
left join public.organizations lb on lb.type='local_board' and lb.slug=v.local_board
on conflict(external_id) do update set name=excluded.name,school_name=excluded.school_name,slug=excluded.slug,
  organization_number=excluded.organization_number,county=excluded.county,local_board_id=excluded.local_board_id,
  school_level=excluded.school_level,contact_email=excluded.contact_email,status=excluded.status;

-- Fylkesstyret inneholder skolene i fylket.
insert into public.organization_relations(parent_id,child_id,relation_type)
select f.id,s.id,'county_contains'
from public.organizations s
join public.organizations f on f.type='county_board' and f.county=s.county and f.external_id like 'eo-fylke-%'
where s.type='school' and s.external_id like 'eo-skole-%'
on conflict(parent_id,child_id,relation_type) do nothing;
