'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Bell, CalendarDays, Check, ChevronDown, CircleHelp, FileDown, FileUp, Flag, Heart, Home, ImagePlus, LockKeyhole, Menu, MessageCircle, MoreHorizontal, Plus, Search, Send, Settings, ShieldCheck, Sparkles, UserRound, Users, Vote, X } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { conversations as initialConversations, events, initialPosts, organizations as initialOrganizations, representations, searchResults } from '@/lib/demo-data';
import type { Audience, Conversation, Event, Organization, Post, Representation } from '@/lib/domain/types';

type View = 'feed'|'explore'|'events'|'event'|'messages'|'profile'|'organization'|'admin'|'legal';
type ComposerMode = 'post'|'poll';
const navItems:{id:View;label:string;icon:typeof Home}[]=[{id:'feed',label:'Hjem',icon:Home},{id:'explore',label:'Utforsk',icon:Search},{id:'events',label:'Arrangementer',icon:CalendarDays},{id:'messages',label:'Meldinger',icon:MessageCircle},{id:'profile',label:'Profil',icon:UserRound}];

declare global { interface Document { modelContext?: { registerTool:(tool:{name:string;title?:string;description:string;inputSchema:object;annotations?:{readOnlyHint?:boolean;untrustedContentHint?:boolean};execute:(input:unknown)=>unknown},options?:{signal?:AbortSignal})=>void|Promise<void> } } }

function Logo(){return <span className="brand" aria-label="Elevrådsnett"><span className="brand-mark"><span/></span><span>elevråds<strong>nett</strong></span></span>}
function Avatar({initials,tone='navy',large=false}:{initials:string;tone?:'navy'|'coral'|'pale';large?:boolean}){return <span className={`avatar ${tone} ${large?'large':''}`}>{initials}</span>}
function Status({children,tone='blue'}:{children:React.ReactNode;tone?:'blue'|'coral'|'green'|'gray'}){return <span className={`status ${tone}`}>{children}</span>}

export default function ElevradsnettApp(){
  const [view,setView]=useState<View>('feed');
  const [activeRep,setActiveRep]=useState<Representation>(representations[0]);
  const [repOpen,setRepOpen]=useState(false);
  const [mobileOpen,setMobileOpen]=useState(false);
  const [signedIn,setSignedIn]=useState(true);
  const [loginOpen,setLoginOpen]=useState(false);
  const [composerOpen,setComposerOpen]=useState(false);
  const [composerMode,setComposerMode]=useState<ComposerMode>('post');
  const [composerText,setComposerText]=useState('');
  const [composerAudience,setComposerAudience]=useState<Audience>('public');
  const [posts,setPosts]=useState<Post[]>(initialPosts);
  const [organizations,setOrganizations]=useState<Organization[]>(initialOrganizations);
  const [feedMode,setFeedMode]=useState<'recommended'|'chronological'>('recommended');
  const [liked,setLiked]=useState<string[]>([]);
  const [commentsOpen,setCommentsOpen]=useState<string[]>([]);
  const [commentDraft,setCommentDraft]=useState('');
  const [votes,setVotes]=useState<Record<string,string>>({});
  const [query,setQuery]=useState('');
  const [showInactive,setShowInactive]=useState(false);
  const [selectedOrg,setSelectedOrg]=useState<Organization>(organizations[3]);
  const [selectedEvent,setSelectedEvent]=useState<Event>(events[0]);
  const [going,setGoing]=useState<string[]>([]);
  const [interested,setInterested]=useState<string[]>([]);
  const [conversations,setConversations]=useState<Conversation[]>(initialConversations);
  const [selectedConversation,setSelectedConversation]=useState(initialConversations[0].id);
  const [messageDraft,setMessageDraft]=useState('');
  const [toast,setToast]=useState('');
  const [legalPage,setLegalPage]=useState<'privacy'|'terms'|'contact'|'cookies'>('privacy');

  const go=useCallback((next:View)=>{setView(next);setMobileOpen(false);window.scrollTo({top:0,behavior:'smooth'})},[]);
  const requireLogin=(action:()=>void)=>{if(!signedIn){setLoginOpen(true);return}action()};
  const notify=(text:string)=>{setToast(text);window.setTimeout(()=>setToast(''),2800)};
  const openOrganization=(id:string)=>{const found=organizations.find(o=>o.id===id);if(found){setSelectedOrg(found);go('organization')}};
  const openEvent=(id:string)=>{const found=events.find(e=>e.id===id);if(found){setSelectedEvent(found);go('event')}};
  const filteredResults=useMemo(()=>searchResults.filter(r=>(showInactive||!r.inactive)&&(!query||`${r.title} ${r.subtitle} ${r.type}`.toLowerCase().includes(query.toLowerCase()))),[query,showInactive]);
  const visiblePosts=useMemo(()=>feedMode==='chronological'?[...posts].reverse():posts,[feedMode,posts]);
  const activeConversation=conversations.find(c=>c.id===selectedConversation)??conversations[0];

  const publish=(status:'draft'|'published')=>{if(!composerText.trim()){notify('Skriv noe før du fortsetter');return}const post:Post={id:`post-${Date.now()}`,organizationId:activeRep.organizationId,initials:activeRep.initials,organizationName:activeRep.name,actorName:'Ida Halvorsen',actorRole:activeRep.publicRole,createdAt:'akkurat nå',body:composerText.trim(),audience:composerAudience,likes:0,comments:0,edited:false};setPosts(all=>[post,...all]);setComposerText('');setComposerOpen(false);notify(status==='draft'?'Utkastet er lagret':'Innlegget er publisert')};
  const sendMessage=()=>{if(!messageDraft.trim())return;setConversations(all=>all.map(c=>c.id===activeConversation.id?{...c,messages:[...c.messages,{id:`m-${Date.now()}`,from:'Ida',mine:true,text:messageDraft.trim(),time:'nå'}]}:c));setMessageDraft('')};
  const share=async(post:Post)=>{const url=`${window.location.origin}/?post=${post.id}`;const shareFn=(navigator as Navigator & {share?: (data:ShareData)=>Promise<void>}).share;try{if(shareFn){await shareFn.call(navigator,{title:`${post.organizationName} på Elevrådsnett`,text:post.body.slice(0,100),url});notify('Deling åpnet')}else{await navigator.clipboard.writeText(url);notify('Lenken er kopiert')}}catch{/* User cancelled */}};

  useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const run=async()=>{await context.registerTool({name:'navigate_elevradsnett',title:'Åpne side',description:'Åpner en hovedside i Elevrådsnett.',inputSchema:{type:'object',properties:{view:{type:'string',enum:['feed','explore','events','messages','profile','admin']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:(input)=>{const value=(input as {view?:string}).view;if(!['feed','explore','events','messages','profile','admin'].includes(value??''))throw new Error('Ugyldig side');go(value as View);return{view:value}}},{signal:lifecycle.signal});await context.registerTool({name:'start_post_creation',title:'Start nytt innlegg',description:'Åpner publiseringsdialogen for aktiv representasjon.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{if(!activeRep.canPublish)throw new Error('Aktiv representasjon har ikke publiseringsrett');setComposerOpen(true);return{organization:activeRep.name,status:'composer_open'}}},{signal:lifecycle.signal})};void run().catch(()=>{});return()=>lifecycle.abort()},[activeRep,go]);

  const Feed=()=> <section className="feed page-enter" aria-labelledby="feed-title">
    <div className="section-heading"><div><p className="eyebrow">{activeRep.name}</p><h1 id="feed-title">Hjem</h1></div><div className="segment" aria-label="Feedtype"><button className={feedMode==='recommended'?'selected':''} onClick={()=>setFeedMode('recommended')}>Anbefalt</button><button className={feedMode==='chronological'?'selected':''} onClick={()=>setFeedMode('chronological')}>Kronologisk</button></div></div>
    <SearchBox onSubmit={()=>go('explore')}/>
    <section className="network-card"><div className="card-title"><div><h2>Nettverk i Oslo</h2><p>Skoler og styrer som er relevante for deg</p></div><button onClick={()=>go('explore')}>Se alle</button></div><div className="org-list">{organizations.filter(o=>o.type==='school'&&o.status==='active').slice(1,4).map(org=><OrganizationMini key={org.id} org={org} onOpen={()=>openOrganization(org.id)} onFollow={()=>requireLogin(()=>{setOrganizations(all=>all.map(o=>o.id===org.id?{...o,following:!o.following}:o));notify(org.following?'Sluttet å følge':'Følger nå')})}/>)}</div></section>
    <div className="feed-title"><h2>Nytt fra elevrådene</h2><span>{feedMode==='recommended'?'Rangert etter relevans':'Nyeste først'}</span></div>
    {visiblePosts.map(post=><PostCard key={post.id} post={post} liked={liked.includes(post.id)} commentsOpen={commentsOpen.includes(post.id)} voted={votes[post.id]} onLike={()=>requireLogin(()=>setLiked(all=>all.includes(post.id)?all.filter(id=>id!==post.id):[...all,post.id]))} onComments={()=>requireLogin(()=>setCommentsOpen(all=>all.includes(post.id)?all.filter(id=>id!==post.id):[...all,post.id]))} onShare={()=>share(post)} onVote={(option)=>requireLogin(()=>setVotes(all=>({...all,[post.id]:option})))} onEvent={()=>post.eventId&&openEvent(post.eventId)} commentDraft={commentDraft} setCommentDraft={setCommentDraft} onSendComment={()=>{if(commentDraft.trim()){setCommentDraft('');notify('Kommentaren er publisert')}}} onOrg={()=>openOrganization(post.organizationId)}/>) }
  </section>;

  const Explore=()=> <section className="feed page-enter"><div><p className="eyebrow">Finn frem</p><h1>Utforsk</h1><p className="lead">Søk i offentlige skoler, styrer, personer, innlegg og arrangementer.</p></div><label className="search-box large"><Search/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} aria-label="Søk i Elevrådsnett" placeholder="Søk etter navn, skole eller tema"/><button onClick={()=>undefined}>Søk</button></label><label className="check-row"><input type="checkbox" checked={showInactive} onChange={e=>setShowInactive(e.target.checked)}/><span>Vis tidligere tillitsvalgte og deaktiverte skoler</span></label><div className="result-list">{filteredResults.length?filteredResults.map(result=><button className="search-result" key={`${result.type}-${result.id}`} onClick={()=>result.type==='Skole'||result.type==='Styre'?openOrganization(result.id):result.type==='Arrangement'?openEvent(result.id):result.type==='Person'?go('messages'):go('feed')}><span className="result-icon">{result.type==='Person'?<UserRound/>:result.type==='Arrangement'?<CalendarDays/>:result.type==='Innlegg'?<MessageCircle/>:<Users/>}</span><span><Status tone={result.inactive?'gray':result.type==='Person'?'green':'blue'}>{result.type}</Status><strong>{result.title}</strong><small>{result.subtitle}</small></span><ChevronDown className="result-arrow"/></button>):<Empty title="Ingen treff" text="Prøv et annet søkeord eller vis tidligere tillitsvalgte."/>}</div></section>;

  const Events=()=> <section className="feed page-enter"><div className="section-heading"><div><p className="eyebrow">Kurs, samlinger og møter</p><h1>Arrangementer</h1></div><button className="outline-action" onClick={()=>notify('Kalenderen er oppdatert')}>Min kalender</button></div><div className="event-grid">{events.map(event=><article className="event-card" key={event.id}><button className="event-visual" onClick={()=>openEvent(event.id)}><span>{event.host==='EO Nasjonalt'?'EO':'OSLO'}</span><Status tone="coral">{event.registered} påmeldte</Status></button><div className="event-body"><p className="event-date">{event.start.split('·')[0]}</p><h2><button onClick={()=>openEvent(event.id)}>{event.title}</button></h2><p>{event.description}</p><div className="event-buttons"><button className={going.includes(event.id)?'primary-button':'outline-action'} onClick={()=>requireLogin(()=>setGoing(all=>all.includes(event.id)?all.filter(id=>id!==event.id):[...all,event.id]))}>{going.includes(event.id)?<><Check/>Skolen er påmeldt</>:'Meld på skolen'}</button><button className={interested.includes(event.id)?'following-button':'outline-action'} onClick={()=>requireLogin(()=>setInterested(all=>all.includes(event.id)?all.filter(id=>id!==event.id):[...all,event.id]))}>{interested.includes(event.id)?'Interessert':'Marker interesse'}</button></div></div></article>)}</div></section>;

  const EventDetail=()=> <section className="feed page-enter"><button className="back-button" onClick={()=>go('events')}><ArrowLeft/>Alle arrangementer</button><div className="event-hero"><div><p>{selectedEvent.host}</p><h1>{selectedEvent.title}</h1><span>{selectedEvent.audience}</span></div></div><div className="detail-card"><div><Status tone="green">{selectedEvent.status==='published'?'Påmelding åpen':selectedEvent.status}</Status><h2>Om arrangementet</h2><p>{selectedEvent.description}</p><dl><div><dt>Når</dt><dd>{selectedEvent.start}<br/>{selectedEvent.end}</dd></div><div><dt>Hvor</dt><dd>{selectedEvent.place}</dd></div><div><dt>Frist</dt><dd>{selectedEvent.deadline}</dd></div><div><dt>Kapasitet</dt><dd>{selectedEvent.registered} av {selectedEvent.capacity}</dd></div></dl></div><aside><button className="primary-button wide" onClick={()=>requireLogin(()=>setGoing(all=>all.includes(selectedEvent.id)?all.filter(id=>id!==selectedEvent.id):[...all,selectedEvent.id]))}>{going.includes(selectedEvent.id)?'Påmelding registrert':'Meld på skolen'}</button><p>Skoleadministrator registrerer delegater. Bare bekreftet deltakelse legges til på CV-en.</p></aside></div></section>;

  const Messages=()=> <section className="messages-view page-enter"><div className="messages-sidebar"><div className="messages-heading"><div><p className="eyebrow">Personlige samtaler</p><h1>Meldinger</h1></div><button aria-label="Ny samtale" onClick={()=>notify('Personsøk er åpnet')}><Plus/></button></div><label className="mini-search"><Search/><input aria-label="Søk etter personer" placeholder="Søk etter personer eller skole"/></label><div className="conversation-list">{conversations.map(c=><button className={c.id===activeConversation.id?'active':''} key={c.id} onClick={()=>{setSelectedConversation(c.id);setConversations(all=>all.map(x=>x.id===c.id?{...x,unread:0}:x))}}><Avatar initials={c.initials} tone={c.kind==='managed'?'coral':'navy'}/><span><strong>{c.name}</strong><small>{c.kind==='managed'?'Systemadministrert gruppe':`${c.members} deltakere`}</small></span>{c.unread>0&&<b>{c.unread}</b>}</button>)}</div></div><div className="chat-panel"><header><Avatar initials={activeConversation.initials} tone={activeConversation.kind==='managed'?'coral':'navy'}/><div><h2>{activeConversation.name}</h2><p>{activeConversation.kind==='managed'?'Medlemskap følger aktive verv':`${activeConversation.members} deltakere`}</p></div><button aria-label="Samtaleinnstillinger"><MoreHorizontal/></button></header>{activeConversation.kind==='managed'&&<div className="privacy-strip"><LockKeyhole/>Nye medlemmer ser meldinger fra datoen de blir lagt til.</div>}<div className="message-history" aria-live="polite">{activeConversation.messages.map(m=><div className={`message ${m.mine?'mine':''}`} key={m.id}><strong>{m.mine?'Du':m.from}</strong><p>{m.text}</p><time>{m.time}</time></div>)}</div><form className="message-composer" onSubmit={e=>{e.preventDefault();sendMessage()}}><button type="button" aria-label="Legg ved fil"><Plus/></button><input value={messageDraft} onChange={e=>setMessageDraft(e.target.value)} aria-label="Skriv melding" placeholder="Skriv en melding…"/><button className="send-button" aria-label="Send melding"><Send/></button></form></div></section>;

  const Profile=()=> <section className="feed page-enter"><div className="profile-hero"><Avatar initials="IH" large/><div><h1>Ida Halvorsen</h1><p>Elvebakken vgs · Oslo</p></div><button className="outline-action" onClick={()=>notify('Profilinnstillinger åpnet')}><Settings/>Rediger profil</button></div><div className="stats-row"><div><strong>3</strong><span>Offentlige verv</span></div><div><strong>7</strong><span>Bekreftede arrangementer</span></div><div><strong>2 ★</strong><span>Elevting</span></div></div><section className="content-card"><div className="card-title"><div><h2>Representasjoner</h2><p>Én er aktiv om gangen. Meldinger er alltid personlige.</p></div></div>{representations.map(rep=><div className="role-row" key={rep.id}><Avatar initials={rep.initials} tone={rep.id===activeRep.id?'coral':'navy'}/><div><strong>{rep.name}</strong><span>{rep.publicRole}</span></div>{rep.id===activeRep.id?<Status tone="coral">Aktiv</Status>:<button onClick={()=>{setActiveRep(rep);notify(`Byttet til ${rep.name}`)}}>Bytt</button>}</div>)}</section><section className="content-card"><h2>CV og historikk</h2><div className="timeline"><div><span>2026–nå</span><strong>Elevrådsleder</strong><p>Elvebakken vgs</p></div><div><span>2025–2026</span><strong>Elevrådsmedlem</strong><p>Elvebakken vgs</p></div><div><span>30. okt. 2025</span><strong>Elevtinget 2025 ★</strong><p>Bekreftet delegat for Elvebakken vgs</p></div></div></section></section>;

  const OrganizationView=()=> <section className="feed page-enter"><div className={`org-cover ${selectedOrg.status==='deactivated'?'inactive':''}`}><span className="cover-pattern"/><div><Avatar initials={selectedOrg.initials} tone={selectedOrg.type==='national'?'coral':'navy'} large/><div><p>{selectedOrg.type==='school'?'Skole og elevråd':selectedOrg.type==='county_board'?'Fylkesstyre':selectedOrg.type==='local_board'?'Lokallag':'Elevorganisasjonen'}</p><h1>{selectedOrg.name}</h1><span>{selectedOrg.county}{selectedOrg.localBoard?` · ${selectedOrg.localBoard}`:''}</span></div></div>{selectedOrg.status==='deactivated'&&<Status tone="gray">Deaktivert</Status>}</div><div className="org-actions"><button className="primary-button" onClick={()=>requireLogin(()=>{setOrganizations(all=>all.map(o=>o.id===selectedOrg.id?{...o,following:!o.following}:o));setSelectedOrg(o=>({...o,following:!o.following}))})}>{selectedOrg.following?'Følger':'Følg'}</button><button className="outline-action" onClick={()=>{go('messages');notify('Viser offentlige kontaktpersoner')}}><MessageCircle/>Kontakt personer</button></div><section className="content-card"><h2>Om</h2><p className="body-copy">{selectedOrg.bio}</p><div className="stats-row compact"><div><strong>{selectedOrg.followers}</strong><span>Følgere</span></div><div><strong>8</strong><span>Aktive verv</span></div><div><strong>14</strong><span>Arrangementer</span></div></div></section><section className="content-card"><div className="card-title"><div><h2>Offentlige tillitsvalgte</h2><p>Tekniske rettigheter vises ikke offentlig.</p></div></div>{['Ida Halvorsen · Elevrådsleder','Aksel Vangen · Nestleder','Lea Tran · Elevrådsmedlem'].map((name,i)=><div className="person-row" key={name}><Avatar initials={['IH','AV','LT'][i]} tone={i===0?'coral':'pale'}/><strong>{name}</strong></div>)}</section></section>;

  const Admin=()=> <section className="admin-page page-enter"><div className="admin-heading"><div><p className="eyebrow">Administrasjon · Elvebakken vgs</p><h1>Administrasjonspanel</h1><p>Rettigheter kontrolleres på nytt for hver serveroperasjon.</p></div><Status tone="green"><ShieldCheck/>Skoleadministrator</Status></div><Tabs defaultValue="overview"><TabsList className="admin-tabs"><TabsTrigger value="overview">Oversikt</TabsTrigger><TabsTrigger value="handover">Styreoverføring</TabsTrigger><TabsTrigger value="roles">Roller og verv</TabsTrigger><TabsTrigger value="schools">Skoler</TabsTrigger><TabsTrigger value="moderation">Moderering</TabsTrigger><TabsTrigger value="import">CSV</TabsTrigger></TabsList><TabsContent value="overview"><AdminOverview/></TabsContent><TabsContent value="handover"><Handover onNotify={notify}/></TabsContent><TabsContent value="roles"><Roles onNotify={notify}/></TabsContent><TabsContent value="schools"><Schools onNotify={notify}/></TabsContent><TabsContent value="moderation"><Moderation onNotify={notify}/></TabsContent><TabsContent value="import"><CsvImport onNotify={notify}/></TabsContent></Tabs></section>;

  const Legal=()=> <section className="legal-page page-enter"><div className="legal-nav"><h1>Informasjon</h1>{([['privacy','Personvern'],['terms','Vilkår'],['cookies','Informasjonskapsler'],['contact','Kontakt']] as const).map(([id,label])=><button className={legalPage===id?'active':''} key={id} onClick={()=>setLegalPage(id)}>{label}</button>)}</div><article className="legal-copy">{legalPage==='privacy'?<><p className="eyebrow">Sist oppdatert 9. september 2026</p><h2>Personvernerklæring</h2><p>Elevorganisasjonen er behandlingsansvarlig for Elevrådsnett. Vi behandler kontoopplysninger, skole- og vervstilknytning, offentlig aktivitet, arrangementsdeltakelse og nødvendige tekniske logger for å levere og sikre tjenesten.</p><h3>Dine rettigheter</h3><p>Du kan be om innsyn, retting, eksport, deaktivering eller sletting. Historiske verv og nødvendig revisjonshistorikk kan beholdes når vi har et dokumentert rettslig grunnlag.</p><h3>Private meldinger</h3><p>Meldinger er bare tilgjengelige for aktive samtalemedlemmer. Administratorer kan ikke lese meldinger, med mindre en bruker aktivt rapporterer konkret innhold.</p></>:legalPage==='terms'?<><h2>Vilkår for bruk</h2><p>Bruk Elevrådsnett med respekt for andre. Innlegg og kommentarer publiseres på vegne av organisasjonen du aktivt representerer. Misbruk kan føre til begrensning eller deaktivering.</p><h3>Publisering</h3><p>Du må ha et aktivt verv og eksplisitt publiseringsrett i organisasjonen. Elevrådsnett lagrer hvem som utførte handlingen.</p></>:legalPage==='cookies'?<><h2>Informasjonskapsler og sporing</h2><p>Tjenesten bruker bare strengt nødvendig lokal lagring og innloggingsdata for autentisering, sikkerhet og sesjon. Derfor vises ikke et unødvendig samtykkebanner.</p><p>Valgfri analyse er ikke aktivert. Dersom dette tas i bruk senere, vil den være avslått frem til du velger formål og gir samtykke.</p></>:<><h2>Kontakt</h2><p>Spørsmål om tjenesten, personvern eller sikkerhet kan sendes til <a href="mailto:teknisk@elev.no">teknisk@elev.no</a>.</p><h3>Rapporter innhold</h3><p>Bruk rapporteringsvalget på innlegget, profilen eller mediet. For meldinger deles bare innholdet du aktivt velger.</p></>}</article></section>;

  return <div className="app-shell">
    <header className="topbar"><div className="topbar-inner"><button className="logo-button" onClick={()=>go('feed')}><Logo/></button><nav className="desktop-nav" aria-label="Hovedmeny">{navItems.map(item=><button key={item.id} className={`nav-item ${view===item.id?'active':''}`} onClick={()=>go(item.id)}><item.icon/>{item.label}{item.id==='messages'&&<span className="count">2</span>}</button>)}</nav><button className="icon-button" aria-label="Varsler" onClick={()=>notify('Du har 3 nye varsler')}><Bell/><span className="notice-dot"/></button><div className="rep-wrap"><button className="representation" onClick={()=>setRepOpen(!repOpen)} aria-expanded={repOpen}><Avatar initials={activeRep.initials} tone="coral"/><span><small>Publiserer som</small>{activeRep.name}</span><ChevronDown/></button>{repOpen&&<div className="rep-menu" role="menu">{representations.map(rep=><button key={rep.id} onClick={()=>{setActiveRep(rep);setRepOpen(false);notify(`Aktiv representasjon: ${rep.name}`)}}><Avatar initials={rep.initials} tone={rep.id===activeRep.id?'coral':'navy'}/><span><strong>{rep.name}</strong><small>{rep.publicRole}{!rep.canPublish?' · Kan ikke publisere':''}</small></span>{rep.id===activeRep.id&&<Check/>}</button>)}</div>}</div><button className="primary-button new-post" onClick={()=>requireLogin(()=>activeRep.canPublish?setComposerOpen(true):notify('Denne representasjonen har ikke publiseringsrett'))}>Nytt innlegg</button><button className="mobile-menu" aria-label="Meny" onClick={()=>setMobileOpen(!mobileOpen)}>{mobileOpen?<X/>:<Menu/>}</button></div>{mobileOpen&&<nav className="mobile-nav">{navItems.map(item=><button key={item.id} onClick={()=>go(item.id)}><item.icon/>{item.label}</button>)}<button onClick={()=>go('admin')}><ShieldCheck/>Administrasjon</button></nav>}</header>
    <main className={view==='messages'||view==='admin'||view==='legal'?'wide-main':'main-grid'}>{view==='feed'?<><Feed/><RightRail onView={go} activeRep={activeRep}/></>:view==='explore'?<><Explore/><RightRail onView={go} activeRep={activeRep}/></>:view==='events'?<><Events/><RightRail onView={go} activeRep={activeRep}/></>:view==='event'?<><EventDetail/><RightRail onView={go} activeRep={activeRep}/></>:view==='messages'?<Messages/>:view==='profile'?<><Profile/><RightRail onView={go} activeRep={activeRep}/></>:view==='organization'?<><OrganizationView/><RightRail onView={go} activeRep={activeRep}/></>:view==='admin'?<Admin/>:<Legal/>}</main>
    <footer><div><Logo/><p>En trygg sosial plattform for elevdemokratiet.</p></div><nav aria-label="Juridisk"><button onClick={()=>{setLegalPage('privacy');go('legal')}}>Personvern</button><button onClick={()=>{setLegalPage('terms');go('legal')}}>Vilkår</button><button onClick={()=>{setLegalPage('cookies');go('legal')}}>Informasjonskapsler</button><button onClick={()=>{setLegalPage('contact');go('legal')}}>Kontakt</button><button onClick={()=>go('admin')}>Administrasjon</button></nav><span>© 2026 Elevorganisasjonen</span></footer>
    <Composer open={composerOpen} onOpenChange={setComposerOpen} mode={composerMode} setMode={setComposerMode} activeRep={activeRep} text={composerText} setText={setComposerText} audience={composerAudience} setAudience={setComposerAudience} onPublish={publish}/>
    <Login open={loginOpen} onOpenChange={setLoginOpen} onLogin={()=>{setSignedIn(true);setLoginOpen(false);notify('Du er logget inn. Fortsett der du slapp.')}}/>
    {toast&&<div className="toast" role="status"><Check/>{toast}</div>}
  </div>;
}

function SearchBox({onSubmit}:{onSubmit:()=>void}){const [value,setValue]=useState('');return <form className="search-box" onSubmit={e=>{e.preventDefault();onSubmit()}}><Search/><input value={value} onChange={e=>setValue(e.target.value)} aria-label="Søk" placeholder="Søk etter skoler, personer, innlegg eller arrangementer"/><button>Søk</button></form>}
function OrganizationMini({org,onOpen,onFollow}:{org:Organization;onOpen:()=>void;onFollow:()=>void}){return <article className="org-row"><button className="org-main" onClick={onOpen}><Avatar initials={org.initials}/><span><strong>{org.name}</strong><small>{org.schoolLevel==='upper_secondary'?'Videregående':'Ungdomsskole'} · {org.county}</small></span></button><button className={org.following?'following-button':'outline-button'} onClick={onFollow}>{org.following?'Følger':'Følg'}</button></article>}
function PostCard({post,liked,commentsOpen,voted,onLike,onComments,onShare,onVote,onEvent,commentDraft,setCommentDraft,onSendComment,onOrg}:{post:Post;liked:boolean;commentsOpen:boolean;voted?:string;onLike:()=>void;onComments:()=>void;onShare:()=>void;onVote:(id:string)=>void;onEvent:()=>void;commentDraft:string;setCommentDraft:(v:string)=>void;onSendComment:()=>void;onOrg:()=>void}){const total=post.poll?.options.reduce((n,o)=>n+o.votes,0)??0;return <article className="post-card">{post.priority&&<div className="priority"><Sparkles/>Prioritert fra EO</div>}<div className="post-head"><button onClick={onOrg}><Avatar initials={post.initials} tone={post.organizationId==='eo'?'coral':'navy'}/></button><div><button className="text-button" onClick={onOrg}><strong>{post.organizationName}</strong></button><p>{post.actorName} · {post.actorRole} · {post.createdAt}{post.edited?' · redigert':''}</p></div><button aria-label="Flere valg"><MoreHorizontal/></button></div><p className="post-copy">{post.body}</p>{post.eventId&&<button className="event-chip" onClick={onEvent}><CalendarDays/><span><strong>Elevtinget 2026</strong><small>30. oktober–1. november · Oslo</small></span></button>}{post.poll&&<div className="poll"><strong>{post.poll.question}</strong>{post.poll.options.map(option=>{const pct=Math.round(option.votes/total*100);return <button key={option.id} onClick={()=>onVote(option.id)} disabled={Boolean(voted)}><span className="poll-fill" style={{width:`${pct}%`}}/><span>{option.label}<b>{voted?`${pct}%`:''}</b></span>{voted===option.id&&<Check/>}</button>})}<small>{voted?'Stemmen din er registrert. Du kan endre den frem til fristen.':`Én stemme per organisasjon · avsluttes ${post.poll.closesAt}`}</small></div>}<div className="post-actions"><button className={liked?'liked':''} onClick={onLike}><Heart/> {post.likes+(liked?1:0)}</button><button onClick={onComments}><MessageCircle/> {post.comments}</button><button onClick={onShare} aria-label="Del innlegget"><Send/></button><button aria-label="Rapporter innlegget"><Flag/></button><span className="audience-label">{post.audience==='public'?'Offentlig':post.audience==='county'?'Eget fylke':post.audience==='local'?'Eget lokallag':'Venneråd'}</span></div>{commentsOpen&&<div className="comments"><div className="comment"><Avatar initials="SN" tone="pale"/><div><strong>Kongshavn vgs <span>· Sofie Nilsen</span></strong><p>Vi bruker korte klassesbesøk før store saker. Det senker terskelen mye.</p></div></div><form onSubmit={e=>{e.preventDefault();onSendComment()}}><Avatar initials="EV"/><input value={commentDraft} onChange={e=>setCommentDraft(e.target.value)} aria-label="Skriv kommentar" placeholder="Kommenter som Elvebakken vgs…"/><button>Send</button></form></div>}</article>}
function RightRail({onView,activeRep}:{onView:(v:View)=>void;activeRep:Representation}){return <aside className="right-rail"><section className="profile-card"><div className="profile-top"><Avatar initials="IH" large/><div><h2>Ida Halvorsen</h2><p>{activeRep.publicRole}</p></div></div><div className="active-context"><span>Aktiv representasjon</span><strong>{activeRep.name}</strong><small>{activeRep.canPublish?'Kan publisere':'Ingen publiseringsrett'}</small></div><button className="wide-button" onClick={()=>onView('profile')}>Se profil og bytt <ChevronDown/></button></section><section className="mini-card"><div className="card-title"><h2>Kommende</h2><button onClick={()=>onView('events')}>Se alle</button></div><div className="upcoming"><span><strong>18</strong><small>SEP</small></span><div><h3>Skolering for elevråd</h3><p>I morgen · Oslo</p></div></div><div className="upcoming"><span><strong>30</strong><small>OKT</small></span><div><h3>Elevtinget 2026</h3><p>Om 6 uker · Oslo</p></div></div></section><section className="info-note"><strong>Styreoverføring om 46 dager</strong><p>Registrer neste styre før 25. oktober. Minst én ny administrator må akseptere.</p><button onClick={()=>onView('admin')}>Gå til administrasjon</button></section></aside>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><CircleHelp/><h2>{title}</h2><p>{text}</p></div>}

function Composer({open,onOpenChange,mode,setMode,activeRep,text,setText,audience,setAudience,onPublish}:{open:boolean;onOpenChange:(v:boolean)=>void;mode:ComposerMode;setMode:(v:ComposerMode)=>void;activeRep:Representation;text:string;setText:(v:string)=>void;audience:Audience;setAudience:(v:Audience)=>void;onPublish:(s:'draft'|'published')=>void}){return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="composer-dialog"><DialogHeader><DialogTitle>Nytt innlegg</DialogTitle><DialogDescription>Innlegget publiseres offentlig av organisasjonen. Navnet ditt lagres og vises under.</DialogDescription></DialogHeader><div className="publisher"><Avatar initials={activeRep.initials} tone="coral"/><span><small>Du publiserer som</small><strong>{activeRep.name}</strong><em>Ida Halvorsen · {activeRep.publicRole}</em></span></div><div className="composer-tabs"><button className={mode==='post'?'active':''} onClick={()=>setMode('post')}>Innlegg</button><button className={mode==='poll'?'active':''} onClick={()=>setMode('poll')}><Vote/>Avstemning</button></div><label className="field"><span>Tekst</span><textarea autoFocus value={text} onChange={e=>setText(e.target.value)} placeholder="Hva vil dere dele?" rows={6}/><small>{text.length}/6000</small></label>{mode==='poll'&&<div className="poll-builder"><label className="field"><span>Spørsmål</span><input placeholder="Hva vil dere spørre om?"/></label><label className="field"><span>Svaralternativer</span><input placeholder="Alternativ 1"/><input placeholder="Alternativ 2"/></label></div>}<div className="composer-options"><label className="field"><span>Målgruppe</span><select value={audience} onChange={e=>setAudience(e.target.value as Audience)}><option value="public">Offentlig</option><option value="county">Skoler i eget fylke</option><option value="local">Skoler i eget lokallag</option><option value="friends">Venneråd</option></select></label><button className="media-button"><ImagePlus/>Legg til bilde eller video</button></div><DialogFooter className="dialog-footer"><button className="outline-action" onClick={()=>onPublish('draft')}>Lagre utkast</button><button className="primary-button" onClick={()=>onPublish('published')}>Publiser som {activeRep.name}</button></DialogFooter></DialogContent></Dialog>}
function Login({open,onOpenChange,onLogin}:{open:boolean;onOpenChange:(v:boolean)=>void;onLogin:()=>void}){return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="login-dialog"><DialogHeader><DialogTitle>Logg inn for å fortsette</DialogTitle><DialogDescription>Etter innlogging kommer du tilbake til handlingen du startet.</DialogDescription></DialogHeader><label className="field"><span>E-post</span><input type="email" placeholder="navn@eksempel.no"/></label><label className="field"><span>Passord</span><input type="password" placeholder="••••••••"/></label><button className="primary-button wide" onClick={onLogin}>Logg inn</button><button className="text-button">Opprett konto og velg skole</button></DialogContent></Dialog>}

function AdminOverview(){return <div className="admin-content"><div className="metric-grid">{[['12','Aktive medlemmer','+2 siste måned'],['8','Publiserte innlegg','3 utkast'],['4','Arrangementer','2 kommende'],['46','Dager til styreskifte','25. oktober']].map(([n,l,s])=><article key={l}><strong>{n}</strong><span>{l}</span><small>{s}</small></article>)}</div><div className="admin-columns"><section className="content-card"><h2>Oppgaver</h2>{[['Inviter ny skoleadministrator','Anbefalt før styreskiftet','coral'],['Bekreft delegater','Skolering for elevråd','blue'],['Gjennomgå to rapporter','Moderering','gray']].map(([t,s,c])=><button className="task-row" key={t}><Status tone={c as 'coral'|'blue'|'gray'}>{c==='coral'?'Viktig':'Åpen'}</Status><span><strong>{t}</strong><small>{s}</small></span><ChevronDown/></button>)}</section><section className="content-card"><h2>Nylige handlinger</h2>{['Ida oppdaterte skolens biografi','Aksel publiserte et innlegg','Sofie aksepterte et offentlig verv','Ida registrerte valgdato'].map((text,i)=><div className="audit-row" key={text}><span/><div><strong>{text}</strong><small>{i===0?'for 12 min siden':`${i+1} dager siden`}</small></div></div>)}</section></div></div>}
function Handover({onNotify}:{onNotify:(s:string)=>void}){const [step,setStep]=useState(1);return <div className="admin-content"><section className="handover-card"><div className="handover-progress">{['Dato','Nytt styre','Rettigheter','Forhåndsvisning'].map((s,i)=><div className={step>=i+1?'active':''} key={s}><span>{step>i+1?<Check/>:i+1}</span><small>{s}</small></div>)}</div><div className="handover-body">{step===1?<><p className="eyebrow">Steg 1 av 4</p><h2>Bekreft styreskiftet</h2><p>Nåværende administrator beholder nødvendig tilgang til minst én etterfølger har akseptert.</p><label className="field"><span>Dato for styreskifte</span><input type="date" defaultValue="2026-10-25"/></label><label className="field"><span>Sluttdato for gammelt styre</span><input type="date" defaultValue="2026-10-24"/></label></>:step===2?<><p className="eyebrow">Steg 2 av 4</p><h2>Velg det nye styret</h2>{['Sofie Nilsen · foreslått leder','Aksel Vangen · foreslått nestleder','Lea Tran · foreslått medlem'].map(x=><label className="member-choice" key={x}><input type="checkbox" defaultChecked/><Avatar initials={x.split(' ').map(v=>v[0]).slice(0,2).join('')}/><span>{x}</span></label>)}<button className="outline-action"><Plus/>Inviter ny bruker</button></>:step===3?<><p className="eyebrow">Steg 3 av 4</p><h2>Fordel tekniske rettigheter</h2><label className="field"><span>Ny skoleadministrator</span><select defaultValue="sofie"><option value="sofie">Sofie Nilsen</option><option value="aksel">Aksel Vangen</option></select></label><label className="member-choice"><input type="checkbox" defaultChecked/><span>Behold Ida som administrator frem til Sofie har akseptert</span></label><label className="member-choice"><input type="checkbox"/><span>Gi Aksel rollen innholdsansvarlig</span></label></>:<><p className="eyebrow">Steg 4 av 4</p><h2>Kontroller overføringen</h2><div className="preview-list"><p><strong>25. oktober:</strong> Nytt styre aktiveres</p><p><strong>Sofie Nilsen:</strong> Elevrådsleder og skoleadministrator</p><p><strong>Ida Halvorsen:</strong> Verv avsluttes etter akseptert etterfølger</p><p><strong>Revisjonslogg:</strong> Alle endringer registreres</p></div></>}</div><div className="handover-actions"><button className="outline-action" disabled={step===1} onClick={()=>setStep(v=>Math.max(1,v-1))}>Tilbake</button><button className="primary-button" onClick={()=>step<4?setStep(v=>v+1):onNotify('Overføringen er sendt til godkjenning')}>{step<4?'Neste':'Send invitasjoner'}</button></div></section></div>}
function Roles({onNotify}:{onNotify:(s:string)=>void}){return <div className="admin-content"><section className="content-card"><div className="card-title"><div><h2>Roller og offentlige verv</h2><p>Tekniske rettigheter og offentlige verv administreres separat.</p></div><button onClick={()=>onNotify('Skjema for ny rolle åpnet')}>+ Tildel rolle</button></div><div className="admin-table" role="table"><div className="table-head" role="row"><span>Person</span><span>Offentlig verv</span><span>Intern rettighet</span><span>Status</span></div>{[['Ida Halvorsen','Elevrådsleder','Skoleadministrator'],['Aksel Vangen','Nestleder','Innholdsansvarlig'],['Lea Tran','Elevrådsmedlem','Ingen']].map((r,i)=><div className="table-row" role="row" key={r[0]}><span><Avatar initials={r[0].split(' ').map(v=>v[0]).join('')}/><strong>{r[0]}</strong></span><span>{r[1]}</span><span>{r[2]}{i===1&&<LockKeyhole/>}</span><span><Status tone="green">Aktiv</Status></span></div>)}</div></section></div>}
function Schools({onNotify}:{onNotify:(s:string)=>void}){return <div className="admin-content"><section className="content-card"><div className="card-title"><div><h2>Skoleadministrasjon</h2><p>Deaktivering bevarer innlegg, verv og arrangementhistorikk.</p></div></div><div className="admin-table"><div className="table-head"><span>Skole</span><span>Lokallag</span><span>Administratorer</span><span>Status</span></div>{[['Elvebakken vgs','Oslo Sentrum','2','Aktiv'],['Oslo Handelsgymnasium','Oslo Sentrum','1','Aktiv'],['Fagerborg skole','Oslo Vest','0','Deaktivert']].map(r=><button className="table-row" key={r[0]} onClick={()=>onNotify(`Åpnet ${r[0]}`)}><span><strong>{r[0]}</strong></span><span>{r[1]}</span><span>{r[2]}</span><span><Status tone={r[3]==='Aktiv'?'green':'gray'}>{r[3]}</Status></span></button>)}</div></section></div>}
function Moderation({onNotify}:{onNotify:(s:string)=>void}){return <div className="admin-content"><section className="content-card"><div className="card-title"><div><h2>Modereringskø</h2><p>Private meldinger vises bare når konkret innhold er rapportert.</p></div><Status tone="coral">2 åpne</Status></div>{[['Innlegg','Upassende språk','Kongshavn vgs'],['Profil','Feilaktig verv','Tidligere tillitsvalgt']].map(r=><div className="moderation-row" key={r[1]}><Flag/><span><Status tone="gray">{r[0]}</Status><strong>{r[1]}</strong><small>{r[2]} · rapportert i går</small></span><button className="outline-action" onClick={()=>onNotify('Modereringssaken er åpnet')}>Behandle</button></div>)}</section></div>}
function CsvImport({onNotify}:{onNotify:(s:string)=>void}){const [uploaded,setUploaded]=useState(false);return <div className="admin-content"><section className="content-card"><div className="card-title"><div><h2>Import og eksport av skoler</h2><p>Skoler oppdateres etter stabil ekstern ID, ikke navn.</p></div><button onClick={()=>onNotify('Tom CSV-mal lastes ned')}><FileDown/>Last ned mal</button></div><button className="upload-zone" onClick={()=>setUploaded(true)}><FileUp/><strong>Last opp UTF-8 CSV</strong><span>Filen valideres uten å endre databasen</span></button>{uploaded&&<div className="import-preview"><div><Status tone="green">24 nye</Status><Status tone="blue">6 endret</Status><Status tone="coral">2 ugyldige</Status></div><p>Forhåndsvisningen er klar. Ugyldige rader må rettes før import.</p><button className="primary-button" onClick={()=>onNotify('Importen krever eksplisitt bekreftelse')}>Gå til bekreftelse</button></div>}</section></div>}
